### ISSUE TITLE
ipcluster

### ISSUE THREAD

**Issue by josh-gree** [ipython/ipyparallel#104]
Hi,

I am trying to get ipcluster to work on my universities cluster (which uses torque as its batch system). The issue I am facing is that since the startup of the ipengines is done in array job they do not necessarily start at the same time (this means that I have a lot of idle time waiting for all the engines to come up). Has anybody got any ideas about how to mitigate this problem - it would be ideal if the job waits in the queue until all resources are available and then starts the engines and the controller rather than only starting a few engines and then waiting for more resources...

Also no matter what I change in my controller and engine templates I get a walltime of 2hrs - I am currently using qalter to change the walltime after submission which is a pain...

**Comment by minrk** [comment]
I've had the best experience on clusters submitting a single job with a given node/cpu allocation, and then starting the engines with `mpiexec ipengine` in the job file.

**Comment by josh-gree** [comment]
So something along the lines of this?

    #PBS -N ipython
    #PBS -j oe
    #PBS -l walltime=00:00:10
    #PBS -l nodes=2:ppn=16

    module load openmpi/1.6.4/intel

    ipcontroller --log-to-file
    mpiexec -np 31 ipengine --log-to-file

**Comment by minrk** [comment]
Just about, though I often put the Controller in a different job or on a head node, so I don't pass `-np` to mpiexec. That script as-is won't quite work to start the controller and engines both, because you'll need a condition for the controller:

```bash
if [[ $rank = 0 ]]; then # whatever the PBS rank env variable is
 ipcontroller;
else
  mpiexec ...
```

**Comment by josh-gree** [comment]
Thanks very much for your help, I have it all up and running now!

**Comment by minrk** [comment]
@josh-gree thanks! I need to do some writeups for clusters, because often `ipcluster` is *not* the easiest tool for the job.
