### ISSUE TITLE
Ipcontroller doesn't find ipcontroller-engine.json when '--work-dir' flag for c.SSHEngineSetLauncher.engines is set in ipcluster_config.py

### ISSUE THREAD

**Issue by simkovic** [ipython/ipyparallel#109]
My ipcluster_config.py is:

```
projectname='chase'
localuser='matus'
remoteuser='osadmin'
remoteips=['<SERVERIP>']
remoteworkdir='/home/'+remoteuser+'/'+projectname
c.IPClusterEngines.engine_launcher_class = 'SSHEngineSetLauncher'
c.LocalControllerLauncher.controller_args = ["--ip='*'"]
c.SSHEngineSetLauncher.engines={}
for ri in remoteips:
    c.SSHEngineSetLauncher.engines[remoteuser+'@'+ri]=(1,
        ['--work-dir='+remoteworkdir])
print c.SSHEngineSetLauncher.engines
c.SSHLauncher.to_send = [('/home/'+localuser+'/.ipython/profile_'+projectname+'/security/ipcontroller-client.json', 
    '/home/'+remoteuser+'/.ipython/profile_'+projectname+'/security/ipcontroller-client.json'),
    ('/home/'+localuser+'/.ipython/profile_'+projectname+'/security/ipcontroller-engine.json', 
    '/home/'+remoteuser+'/.ipython/profile_'+projectname+'/security/ipcontroller-engine.json')]
```

With` ipcluster start --profile=chase --debug` I get 
```
2016-02-12 20:38:52.691 [IPClusterStart] 2016-02-12 20:38:52.638 [IPEngineApp] Changing to working dir: /home/osadmin/chase
2016-02-12 20:38:52.691 [IPClusterStart] 2016-02-12 20:38:52.638 [IPEngineApp] WARNING | url_file u'.ipython/profile_chase/security/ipcontroller-engine.json' not found
2016-02-12 20:38:52.691 [IPClusterStart] 2016-02-12 20:38:52.638 [IPEngineApp] WARNING | Waiting up to 5.0 seconds for it to arrive.
2016-02-12 20:38:57.703 [IPClusterStart] 2016-02-12 20:38:57.649 [IPEngineApp] CRITICAL | Fatal: url file never arrived: .ipython/profile_chase/security/ipcontroller-engine.json
2016-02-12 20:38:57.721 [IPClusterStart] Connection to <SERVERIP> closed.
2016-02-12 20:38:57.721 [IPClusterStart] Process 'ssh' stopped: {'pid': 13282, 'exit_code': 1}
2016-02-12 20:39:22.409 [IPClusterStart] Engines appear to have started successfully
```

However, `stat -c "%y %s %n" ~/.ipython/profile_chase/security/ipcontroller-engine.json` says `2016-02-12 20:38:52.347508282 +0100 344 /home/osadmin/.ipython/profile_chase/security/ipcontroller-engine.json`

Both client and the remote server are at version 4.1.1

When I omit the --work-dir flag in the config everything works. 

Manual start on server (`ipengine --profile=chase --work-dir=/home/osadmin/chase`) also works. 

Looks like the controller is not looking for ipcontroller-engine.json at the correct location.

**Comment by minrk** [comment]
The gist appears to be that it's using `.ipython` rather than `~/.ipython`, so the path is sensitive to the working directory. This should presumably not be the case.

**Comment by simkovic** [comment]
You are correct. Note though, that I'm setting absolute path in my config file but the controller does not respect my choice and turns it into rel path. Is there a quick fix? Is there an option to ask controller to use absolute paths? Or do I need to tweak the source code? What would be easier/feasible - postpone the change to working directory after the engines are started loaded or force the controller/engines to keep absolute path? Is there any particular reason why the engines work with relative paths?

In addition what is the purpose of the profile-dir? I thought profile-dir is the directory that specifies the location of the config files while the work-dir is the working directory where the code, sent to the engines, is executed.

**Comment by minrk** [comment]
It's probably a bug in the launcher code stripping the path prefix, not taking the working dir into account.

**Comment by simkovic** [comment]
I now have a fix. The solution is simply to set '--profile-dir' for each engine. If the remote profile dir is not set, the launcher guesses that the remote profile dir is a subdirectory of the remote working dir. This is effectively accomplished with the help of `SSHClusterLauncher._strip_home` which is a clumsy hack and should be removed. strip_home makes it impossible for the user to specify the remote user dir by setting `c.SSHClusterLauncher.remote_profile_dir` in the config, which initially confused me. In general a much better guess could be constructed based on the location data of each engine.

**Comment by simkovic** [comment]
I now have a fix. The solution is simply to set '--profile-dir' for each engine. If the remote profile dir is not set, the launcher guesses that the remote profile dir is a subdirectory of the remote working dir. This is effectively accomplished with the help of `SSHClusterLauncher._strip_home` which is a clumsy hack and should be removed. strip_home makes it impossible for the user to specify the remote user dir by setting `c.SSHClusterLauncher.remote_profile_dir` in the config, which initially confused me. In general a much better guess could be constructed based on the location data of each engine.
