### ISSUE TITLE
Yielding results instead of returning

### ISSUE THREAD

**Issue by mbraak** [ipython/ipyparallel#111]
Hello,

We are trying to make it possible to yield results from ipyparallel. This would make it possible to 'stream' the results from a notebook, instead of returning one result.

The python code would look like this:

```python
for i in range(10):
   do_yield(i)
```

Some of our notebooks run for a long time and have very big results. Streaming the results would make that easier.

Would the current architecture of ipyparallel/jupyter allow this?

Marco

**Comment by minrk** [comment]
If I understand corrctly, this is how IPython parallel already works. You can iterate through an AsyncResult, and it will yield results as they arrive.

Can you describe a bit more detail about what you are trying to accomplish?

**Comment by mbraak** [comment]
Thanks for your answer.

I see in the documentation that the `view.map` does indeed have an AsyncResult. Let me see if that works in our situation.

**Comment by mbraak** [comment]
It seems that our use case does not work with `view.map`.

We want something like this:

```python
from ipyparallel import Client

def p():
  for i in range(10):
    do_yield(i)

rc = Client()
view = rc[:]
result = view.apply(p)

for v in result:
  print v
```

I think this is different from `view.map` because in this case it's the applied code that is responsible for the yielding.

The `view.map` alternative is subtly different:

```python
result = view.map(lambda v: v, range(10))

for v in result:
    print v
```

**Comment by minrk** [comment]
Just to clarify from your example above, you want all engines to run the same function `p` with the same arguments?

**Comment by mbraak** [comment]
No, we want 1 engine to run the `p` function.

This would be correct:

```python
rc = Client()
view = rc[0]
```

**Comment by minrk** [comment]
Here's [an example](https://nbviewer.jupyter.org/gist/minrk/1f7f6be52f4c1ee35ad2) of running a generator remotely. The gist is to:

1. call the generator function on the engine
2. create an iterator on the generator
3. use `apply(next, Reference('iterator'))` to yield each item from the remote generator

Then you get a local generator yielding results from a remote generator.

**Comment by mbraak** [comment]
Thanks! This looks very promising.
