### ISSUE TITLE
Increase record limit for DictDB

### ISSUE THREAD

**Issue by mccarthyryanc** [ipython/ipyparallel#125]
Is there a way, perhaps in the controller config, to increase the record limit for DictDB? Or, if I'm going beyond the 1024 limit, should I just switch to the other DB backends?

**Comment by minrk** [comment]
DictDB limits are configurable:

```python
c.DictDB.record_limit = 1024 # maximum number of tasks to store
c.DictDB.size_limit = 1024**3 # max size (in bytes) of stored data
```

You can specify these in `ipcontroller_config.py`. If it's a large amount of tasks, though, DictDB can run into memory problems, and using sqlite or mongo will help:

```python
c.HubFactory.db_class = 'SQLiteDB'
```

But if it's a large number of very small tasks, bumping the record limit on DictDB and relying on the size limit to keep you in reasonable memory should be fine.

**Comment by mccarthyryanc** [comment]
Lots of little tasks is my exact situation. Thanks for spelling out the record/size limit configs, they work as expected!
