### ISSUE TITLE
non-copy sends of numpy arrays taking memory

### ISSUE THREAD

**Issue by samotracio** [ipython/ipyparallel#129]
Hi,
Perhaps I am missing something, but according to the documentation, ipyparallel does non-copy sends when pushing numpy arrays to the engines. Yet when I do

`import ipyparallel as ipp`
`rc = ipp.Client()`
`dv = rc[:]`
`a = np.random.random(5e7)`
`dv.push(dict(a=a))`

I can clearly see each engine process growing by ~380MB.
It this expected ?
If so, is there a way to share (read-only at least) a single copy of the large array among all engines  ?

Thanks and apologizes if this is not the right venue to bring these issues

---

Python 3.5.1 | Anaconda 2.5.0 (64-bit) | IPython 4.1.2 | ipyparallel : 5.0.1

**Comment by minrk** [comment]
I need to clarify what non-copy means somewhere, as it pertains to IPython parallel: copy=False sends don't produce copies within a given process during the serialization/deserialization process. That *does not* mean that it's a zero-copy inter-process shared-memory communication. The best way to accomplish that is with memmapped arrays can accomplish that with memmapped numpy arrays, though. [Here](https://github.com/jupyter/ngcm-tutorial/blob/master/Day-3/examples/memmap.ipynb) is an example of distributing data to machines, and loading with numpy.memmap.

**Comment by samotracio** [comment]
Thanks for the illumination.
May I suggest that adding this to documentation would be very useful. It is far from obvious, at least for rookies like me.

**Comment by minrk** [comment]
I agree 100%, I just haven't figured out the right place. If you would like to make a docs PR to clarify it from your perspective, that would be very welcome.

**Comment by tkchris93** [comment]
The link for the numpy.memmap example you referenced above is broken. Do you have the correct link by chance?

**Comment by minrk** [comment]
[this](https://github.com/jupyter/ngcm-tutorial/blob/524ea8065de366c6e7f04121718cb96c0ed139c5/Part-3/examples/memmap.ipynb) should be a more stable link
