### ISSUE TITLE
Dict literal missing in parallel map

### ISSUE THREAD

**Issue by wxhemiao** [ipython/ipyparallel#139]
I encountered this problem that any dict literal involved in ipyparallel map is missing and becomes `{}` in the output result.

This problem does not impact dict items added via the `update` method and `dict` constructors.

To reproduce the problem, you may spin up a cluster with a direct view called, say dview. The below code was tested in IPython with Python 3.4 (both client and engine).
```
dview.map(lambda x: {'label': x*2}, range(4)}
```
It will return `[{}, {}, {}, {}]`, when you expect the label key to appear in the dict.

The same problem happens as well in the following situations:

- Normal function declaration
- Dict literal used as an intermediate value (even as the argument to update)

**Just realized: This is only reproducible using a remote cluster. Spun up `ipcluster` on local machine, it works fine. Even if I execute `ipython` then `rc = Client()` on the very machine hosting the controller, the above code runs properly.**

**Comment by minrk** [comment]
Like #140, I suspect this is due to a mismatch between the engine and client versions. Make sure that the `ipyparallel` versions are the same.
