### ISSUE TITLE
Map function tries to call list elements

### ISSUE THREAD

**Issue by streamliner18** [ipython/ipyparallel#140]
When calling `map` function with a function/lambda that has a `dict` parameter, `ipyparallel` allegedly calls my list elements (or dict key?) and results in an engine exception.

To reproduce (latest ipyparallel, engine+controller running on Debian, client on Mac. All Python 3.4)

``` python
def test_f(x):
    print({1:x})
dview.map(test_f, range(4)).get()
```

Result:

```
--TypeError                                 Traceback (most recent call last)<string> in <module>()
/usr/local/lib/python3.4/dist-packages/ipyparallel/client/remotefunction.py in <lambda>(f, *sequences)
    229             if self._mapping:
    230                 if sys.version_info[0] >= 3:
--> 231                     f = lambda f, *sequences: list(map(f, *sequences))
    232                 else:
    233                     f = map
<ipython-input-56-b2d79614985f> in test_f(x)
TypeError: 'int' object is not callable
```

If I use something like `print({'1': 'x')})` (Yes it doesn't involve x at all), it becomes `str is not callable`.

Using the lambda version of test_f does not work either.

**Just realized: This is only reproducible using a remote cluster`. Spun up`ipcluster`on local machine, it works fine. Even if I execute`ipython`then`rc = Client()` on the very machine hosting the controller, the above code runs properly.**

**Comment by minrk** [comment]
What is `pip list` (or `conda list`) on engines and the client? I suspect there is a mismatch somewhere that's getting in the way. This code runs fine in my examples.
