### ISSUE TITLE
Request a way to interrupt / abort running tasks either manually or via timeout

### ISSUE THREAD

**Issue by frmdstryr** [ipython/ipyparallel#141]
AsyncResult tasks that have not yet been started can be aborted via the abort() method. However some long running tasks that have already started may need to be cancelled for whatever reason..  Is there any way to send a KeyboardInterrupt (ctrl+c) to interrupt an engine in the middle of a task?

If this were implemented, it would then also be nice to have a way to add a timeout on an AsyncResult so that a task could automatically be interrupted if it doesn't complete within a given amount of time.

**Comment by minrk** [comment]
There is not currently a way to interrupt the engine, though [this proposal](https://github.com/jupyter/enhancement-proposals/pull/14) would create one.

If you are using local engines or otherwise know what machine engines are on, you can interrupt them directly from the client with `os.kill`:

```python
engine_pids = client[:].apply(os.getpid).get_dict()

def signal_engine(engine_id, sig=signal.SIGINT):
    """send a signal to a local engine"""
    pid = engine_pids[engine_id]
    os.kill(pid, sig)
```

You can do the same with `ssh` if the engines are remote.

**Comment by frmdstryr** [comment]
Unfortunately I have to support controllers and remote engines on windows systems that don't have SSH... was hoping for something similar to the  "shutdown" method available to clients. 

Anyways, looks like this is already in the works.

**Comment by frmdstryr** [comment]
Closing as it's already in progress

**Comment by kostrykin** [comment]
Now that more than a year have passed, is there any way of interrupting running tasks/engines?

**Comment by frmdstryr** [comment]
Kind of hackish, but you can spawn an on the system engine normally, but instead of running tasks on that engine, have it spawn it's own local cluster, then "proxy" all the tasks through a client to the local engine. 

I don't have an actual code example. But we used this at my previous job and it worked quite nicely.

**Comment by GF-Huang** [comment]
The `about` method not work.
