### ISSUE TITLE
Is this an error??

### ISSUE THREAD

**Issue by morganw** [ipython/ipyparallel#143]
Hi, 

this is my first time use ipyparallel, and there is an NameError, such as:

>>> import ipyparallel as ipp
>>> rc = ipp.Client()
>>> import numpy as np
>>> def f():
...     return np.zeros((2,2))
... 
>>> f()
array([[ 0.,  0.],
       [ 0.,  0.]])
>>> ar = rc[:].apply_async(f)
>>> pid_map= ar.get_dict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 250, in get_dict
    results = self.get(timeout)
  File "/usr/local/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 160, in get
    raise self.exception()
ipyparallel.error.CompositeError: one or more exceptions from call to method: f
[Engine Exception]NameError: global name 'np' is not defined
[Engine Exception]NameError: global name 'np' is not defined
>>> np
<module 'numpy' from '/usr/local/lib/python2.7/site-packages/numpy/__init__.pyc'>
>>>

**Comment by frmdstryr** [comment]
You have to import numpy on the remote engines. Either use sync imports or add the import to the function definition.

**Comment by morganw** [comment]
ok, thanks
