### ISSUE TITLE
How can I pass kwargs to functions with map?

### ISSUE THREAD

**Issue by ndawe** [ipython/ipyparallel#147]
I can with `apply(f, *args, **kwargs)`, but why not map and others? For a DirectView I get the exception:

```
ces, **kwargs)
    604         for k in kwargs.keys():
    605             if k not in ['block', 'track']:
--> 606                 raise TypeError("invalid keyword arg, %r"%k)
    607 
    608         assert len(sequences) > 0, "must have some sequences to map onto!"

TypeError: invalid keyword arg, ....
```

But for a LoadBalancedView the kwargs are silently swallowed up and I get the wrong function output since the kwargs remain at their defaults. I know I could just make all arguments positional and just include repeated values in `*sequences`, but that isn't very elegant.

**Comment by minrk** [comment]
kwargs with map are ambiguous, which is why they are generally not supported by map interfaces. Should they be partitioned like positional args, or the same value used everywhere? If it's the same value, you can use `functools.partial` (note: for wrapping interactively defined functions, `rc[:].use_cloudpickle()` may be required):

```python
import functools
g = functools.partial(f, kw='value')
view.use_cloudpickle() # may be necessary if f is interactively defined
amr = view.map(g, [positional_args])
```

If you want to map across kwarg values you can build your own wrapper function that takes arg/kwarg bundles as single arguments and passes them to your function:

```python
# turn list of values for a single kwarg into a list of kwarg dicts
a_list = range(10)
kwarg_list = [ dict(a=a) for a in a_list ]

def mappable_f(kwargs):
    """mappable wrapper to unpack kwargs and pass them to f"""
    # import f
    return f(**kwargs)

amr = view.map(mappable_f, kwarg_list)
```

**Comment by ndawe** [comment]
Ah, functools.partial. Thanks for the tip.

This would be helpful in the docs. I'll admit I'm relatively new to ipyparallel and after seeing the signature of apply ``apply(f, *args, **kwargs)`` and explanation that this results in the call ``f(*args, **kwargs)`` I then assumed the same for ``map(f, *args, **kwargs)``. I know the docs mention ``block`` in kwargs but this didn't catch my eye at first:

http://ipyparallel.readthedocs.io/en/latest/api/ipyparallel.html?highlight=map#ipyparallel.DirectView.map

I'm willing to bet that the most common case is where positionals are sequences and kwargs are fixed (same values used across the mapping), like a function with parameters (``**kwargs``) that is evaluated across a grid of points (``*sequences``). Maybe it's worth supporting that "out-of-the-box" like apply()? Or allow kwargs to contain ``f_sequence_kwargs=dict(...)`` and ``f_fixed_kwargs=dict(...)`` (not very appealing IMO)?

**Comment by ndawe** [comment]
Without view.use_cloudpickle() I see the most amusing exception:

```
AttributeError: 'DummyMod' object has no attribute 'foo'
```

Unfortunately it seems cloudpickle can't handle RandomState?

```
ImportError: No module named mtrand
```

**Comment by ndawe** [comment]
Fixed that with:

```python
import sys
sys.path.append(os.path.join(os.path.dirname(np.__file__), 'random'))
```

An issue with ``__qualname__`` in cloudpickle I assume.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. It looks like this issue is resolved. Feel free to open a new Issue if you are still having this trouble. `functools.partial` should be handled natively now without needing to invoke cloudpickle
