### ISSUE TITLE
How to destroy each result item once it is collected when iterating through Asyncresults?

### ISSUE THREAD

**Issue by yifeim** [ipython/ipyparallel#151]
Thanks for the package and many helpful examples. Reading the examples in [Map results are iterable!](http://ipyparallel.readthedocs.io/en/latest/asyncresult.html?highlight=enumerate#map-results-are-iterable), I was wondering if it is possible to also destroy the results once they have been collected, in order to preserve memory. Imagine I am running repeated experiments and all I want is the mean/variance of the results. If I have too many runs, it is quite possible that I cannot host all the intermediate results of all the runs in memory but only the summary statistics.

I guess this feature is somehow implemented already; in the worst case I can initialize a database and delete the items manually or use MPI. If it is implemented as a function call, would you mind explaining it here or in the docs?

OS: Ubuntu 16.04
Python 2.7.11 :: Continuum Analytics, Inc.
ipyparallel: 5.0.1

**Comment by minrk** [comment]
An AsyncMapResult holds a reference to all of its individual results, but if you break it up into an AsyncResult per item, you might be able to clear your references judiciously enough.

As a bit of a hack, you might also be able to reach into the future and delete its reference to the data. Here's an example that *might* work:


```python
amr = view.map(os.urandom, [65535] * 100)
for result, _child in zip(amr, amr._children):
    deal_with(result)
    # clear result storage:
    # amr will no longer be usable after this iteration
    _child._result = None
```

**Comment by yifeim** [comment]
Thanks a lot for the reply! I verified your answer; watching memory usage go up and down is quite a thrilling experience.

Something to add on: the solution seemed to work best on single machine parallelizations; with a ssh profile, my experiment showed that the main memory rss remained high. However, sending GBs of data across network is a dumb idea anyways. I reworked my flow to record only a small part of each run but saved all repetitions (to be able to show other statistics in case of future needs).

Thanks again for answering. It may be a useful example for completeness.

**Comment by yifeim** [comment]
For completeness, here is what I meant by my experiments:

Local experiment (id, memory in GB, time).

```
arr_s = 0.
amr = v.map(gen_large_arr, [1e9] * 10)
tic = time.time()
for i,(result, _child) in enumerate(zip(amr, amr._children)):
    print((i, psutil.Process(os.getpid()).memory_info().rss/1e9, time.time()-tic))
    arr_s = arr_s + result
    _child._result = None

(0, 16.052293632, 22.827470064163208)
(1, 24.052301824, 25.81020760536194)
(2, 16.053927936, 32.12311363220215)
(3, 24.05228544, 41.166239976882935)
(4, 16.054239232, 47.73276734352112)
(5, 24.052350976, 55.67748260498047)
(6, 16.052957184, 63.644251346588135)
(7, 24.05228544, 71.8163845539093)
(8, 16.05851136, 79.43313550949097)
(9, 24.052441088, 83.60173678398132)
```

SSH experiment (id, memory in GB, time):

```
arr_s = 0.
amr = v.map(gen_large_arr, [5e8] * 10)
tic = time.time()
for i,(result, _child) in enumerate(zip(amr, amr._children)):
    print((i, psutil.Process(os.getpid()).memory_info().rss/1e9, time.time()-tic))
    arr_s = arr_s + result
    _child._result = None

(0, 8.052207616, 269.9940674304962)
(1, 40.05220352, 344.79979395866394)
(2, 40.052301824, 346.732474565506)
(3, 40.052301824, 348.4585266113281)
(4, 40.052301824, 350.1269690990448)
(5, 40.052301824, 351.8026645183563)
(6, 40.052301824, 353.4729571342468)
(7, 40.052301824, 355.1532220840454)
(8, 40.05230592, 356.83069467544556)
(9, 40.05230592, 358.51735830307007)
```
