### ISSUE TITLE
The Python standard library function id() has been overwritten

### ISSUE THREAD

**Issue by tkchris93** [ipython/ipyparallel#155]
When I run the following code, I get a the error `TypeError: 'int' object is not callable`

```
import ipyparallel as ipp
rc = ipp.Client()
view = rc[:]
def echo(x):
    return id(x)
view.map_async(echo, range(20)).get()
```

The name `id` has been overwritten. The following code, 

```
def echo2(x):
    return id
view.map_async(echo2, range(20)).get()
```

returns

```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```

I have 20 engines running.

**Comment by minrk** [comment]
This is not done by default, so prior executions will have done this. The namespace is not cleared when you create a new Client connection.

Have you perhaps run something like:

```python
rc[:].scatter('id', rc.ids, flatten=True)
```

before?

You can reset the engine namespace with:

```python
rc[:].execute('%reset')
```
