### ISSUE TITLE
print status message while using map_sync

### ISSUE THREAD

**Issue by samotracio** [ipython/ipyparallel#160]
For simplicity, let's say I want to apply function f to a list using map_sync

    import ipyparallel as ipp
    rc = ipp.Client()
    dv = rc[:]
    def f(i):
        print("processing part "+str(i))
        #do some long calculation with i
        return result(i)
    
    res = dv.map_sync(f, [1,2,3,4,5])

Python blocks until res is returned, but is there a way to print the message on stdout as f is being applied to each element ?  I don't mind if the result is returned all at once at the end, but it would be nice to get a status indicator.
Using asyc_map() it is easy to inspect the stdout of each engine, but the actual calculations are large enough so that running ipyparallel with --nodb is almost mandatory.

Thanks

**Comment by minrk** [comment]
You still get stdout on the async map with `--nodb`. That just changes whether results are retrievable later on, after disconnecting from the cluster. The synchronous APIs are really shorthand for `map|apply_async().get()`. Everything's async underneath.

To do this, I would:

```python
amr = dv.map_async(f, [1,2,3,4,5])
while not amr.wait(1):
    # clear output because we are printing the whole thing each time
    # rather than keeping track of what we've consumed
    clear_output(wait=True)
    for stdout in amr.stdout:
        sys.stdout.write(stdout)

amr.get()
```
