### ISSUE TITLE
fails to bind_kernel when iopub_socket is replaced with IOPubThread

### ISSUE THREAD

**Issue by renewang** [ipython/ipyparallel#164]
Tried to bind_kernel with one active engine but got the following errors:

AttributeError: 'IOPubThread' object has no attribute 'bind_to_random_port'

After walking through code, I found the iopub_socket of engine was replaced with IOPubThread at the time point calling complete_registration and when importing IOPubThread successfully (my ipykernel version is 4.3.1 and ipyparallel is 5.1.0). However, KernelApp._bind_socket called within bind_kernel expect a zmq.socket instance. 

Since I already walked through some ipyparallel and ipkernel codes, I wonder if I could contribute this issue (if it's an issue and it looks quite easy) as a starter when you are busy in big real problems.  
Thanks

**Comment by minrk** [comment]
A PR would be welcome! This should be possible by updating the call to get the actual socket, instead of the IOPubThread (it's available as iopub_thread.socket). You will need to check first, because both ipykernel before/after the IOPubh thread change should still work.

**Comment by minrk** [comment]
Closed by #166
