### ISSUE TITLE
Sending async_apply tasks as a batch

### ISSUE THREAD

**Issue by washougal** [ipython/ipyparallel#169]
I have a workflow that requires a ton of small tasks to be performed. In the hundreds of millions. I have 188 workers fired up on a cluster. Each of the tasks gets saved into a monogodb collection, so nothing on the client side needs to store the async objects. Mongodb is being used for task database.

I've noticed that the biggest bottleneck is sending the individual tasks from the client:

    from ipyparallel import Client
    rc = Client()
    lview = rc[:].load_balanced_view()
    for i, task in enumerate(exceptionally_long_list):
        lview.apply_async(function, **task)
        ...

The tasks are small, and seem to be getting gobbled up by the cluster much faster than they're able to be sent. Even creating a second client, and having both send tasks to the controller simultaneously doesn't keep up. One option would be to combine tasks, and thus each worker completes a group of 10 tasks rather than a single task- but before refactoring, is there some way to send a large number of tasks as a batch?

**Comment by minrk** [comment]
`apply` builds and sends tasks immediately, but you can chunk tasks with `map`, using the keyword argument `chunksize`. So if you had a collection of calls, such as:

```python
def run_task(parameters):
    ...

for i, parameters in enumerate(parameter_space):
    view.apply(run_task, parameters)
```

You could use `map` to submit these in chunks:

```python
amr = view.map(run_task, parameter_space, chunksize=10)
```
