### ISSUE TITLE
__name__ is not defined on a RemoteFunction

### ISSUE THREAD

**Issue by dhirschfeld** [ipython/ipyparallel#175]
Then using the `lview.remote` decorator I'm getting the below error:
```
AttributeError: 'RemoteFunction' object has no attribute '__name__'
```
when wrapping it in another decorator which is obviously expecting the `__name__` attribute to be set.

 I can fairly easily work around it by not using the decorator but it would be nice I guess if it worked...

I see that you also lose the docstring when using the decorator. Perhaps it can be improved by wrapping with the decorator module...

NB: The actual application is attempting to use ipparallel inside pyxll.

**Comment by minrk** [comment]
Should be doable. I'm not sure if we can use the decorator module in this case, but I'll check.
