### ISSUE TITLE
Error on enabling IPython clusters tab extension

### ISSUE THREAD

**Issue by parashardhapola** [ipython/ipyparallel#186]
ipyparallel verion: 5.2.0-py35_0
installed through conda on Python 3.5.2

Got following error on running `ipcluster nbextension enable`

`PermissionError: [Errno 13] Permission denied: '/usr/local/etc/jupyter'`

I do not have root privileges. Please help resolve this issue.

**Comment by minrk** [comment]
To do a per-user install: `ipcluster nbextension enable --user`

The conda package should enable the extension by default, though.

**Comment by damianavila** [comment]
>installed through conda on Python 3.5.2

Are you installing from conda-forge? or default channels?

If it is the second case, I would suggest to use `--sys-prefix` instead of `--user`, otherwise ipyparallel will be enabled in all your environments, even when maybe you will not have ipyparallel installed in all your environments.
