### ISSUE TITLE
client does not terminate running jobs when jupyter kernel interrupts/restarts

### ISSUE THREAD

**Issue by wdwvt1** [ipython/ipyparallel#190]
Our workflow frequently causes us to start clusters with `ipcluster start -n ...` via the shell, open a `jupyter` notebook, and then access a direct view of the started clusters. A simple example:

```bash
ipcluster start -n 2 && jupyter notebook
```
In the jupyter notebook
```python 
from ipyparallel import Client
c = Client()
dv = c[:]

def _f(x):
    import time
    start = time.time()
    time.sleep(10)
    stop = time.time()
    return [x, stop - start]

dv.map_sync(_f, [1, 2])
```

Now, if you run the code snippet above, it will complete in ~10 seconds. Everything as expected. 

Instead, try setting the sleep time to 60 seconds. Start the job, wait for 20 seconds, then interrupt and restart the `jupyter` kernel, and rerun the cell. The job will take 100 seconds to complete: 40 to finish the job started before the restart, and 60 to finish the job just launched.

It seems like the kernal interrupt in `jupyter` does not tell the client to kill its currently running jobs, and new jobs spawned just go into the queue. 

Is this expected behavior? It doesn't seem related to #44 or others, so have opened a new issue.

**Comment by minrk** [comment]
This is the *intended* behavior, whether it is what you expect is a different story. When you interrupt the client's waiting, you *only* interrupt the waiting, not what you are waiting for. Aborting tasks is considered a separate action.

Plus, there is the current limitation that running tasks cannot be interrupted, only queued but not started tasks can be aborted. The upstream KernelNanny proposal will enable us to do remote signaling of engines, giving us the ability to interrupt and restart engines.

Conceptually, interrupting a `_sync` operation aborting its tasks does make sense, and is feasible (short of interrupting the already-running tasks while we wait for remote-signalling capabilities).

**Comment by wdwvt1** [comment]
Thanks @minrk - that makes perfect sense.

**Comment by GF-Huang** [comment]
What's the progress?
