### ISSUE TITLE
AsyncResult has no attribute 'pyout'

### ISSUE THREAD

**Issue by grisaitis** [ipython/ipyparallel#195]
The docs mention an attribute called 'pyout' for the AsyncResult class. It appears this isn't implemented. :(

Source for AsyncResult: https://github.com/ipython/ipyparallel/blob/master/ipyparallel/client/asyncresult.py

Are there plans to implement this? And also, what exactly is it anyway?

**Comment by minrk** [comment]
The docs are a bit out of date on that. There are some fields from the [message protocol](https://jupyter-client.readthedocs.io/en/latest/messaging.html) that are accessible on an AsyncResult. A few of these have been renamed. `.pyout` is now `.execute_result`. You can see it with:

```python
ar = rc.execute('1 + 2', silent=False, block=False)
ar.execute_result
```

It will be a dict, as described in the messaging doc linked above.
