### ISSUE TITLE
jupyter-notebook password error

### ISSUE THREAD

**Issue by tennc** [ipython/ipyparallel#197]
my jupyter-notebook with password and ssl
1. i run `jupyter-notebook`,then i write 'password' to login .
i close my browser,and `ctrl+c` to close 'jupyter-notebook'. (not  logout)
2. i run `jupyter-notebook`, i don't input 'password',i login it.

can you help me ?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time! This doesn't appear to be an IPython parallel question.

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.
