### ISSUE TITLE
error messages only show once in apply_async

### ISSUE THREAD

**Issue by bulik** [ipython/ipyparallel#198]
It seems that I can only get an error traceback once per cluster using apply_sync (or apply_async, or map). After the first error in apply_sync, subsequent errors are recorded as `No traceback available`, which makes debugging tough. Restarting the cluster fixes the problem, but isn't a great solution. Any guidance would be appreciated.

See below for minimal working example. I'm running ipyparallel version 5.2.0.

Thanks!

```
import ipyparallel as ipp
import os
rc = ipp.Client()
dv = rc.direct_view()
def bar():
    raise ValueError('asdf')

dv.apply_sync(bar)
```

[0:apply]
ValueErrorTraceback (most recent call last)<string> in <module>()
<ipython-input-27-3dd61ca8919a> in bar()
ValueError: asdf

[1:apply]
ValueErrorTraceback (most recent call last)<string> in <module>()
<ipython-input-27-3dd61ca8919a> in bar()
ValueError: asdf

```
dv.apply_sync(bar)
```

[0:apply]: 
No traceback available

[1:apply]: 
No traceback available

```
```

**Comment by minrk** [comment]
That's not good! What OS and Python version? What do you get from `pip list` or `conda list`? I'm getting the tracebacks I expect when I run the sample many times.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. I'm going to close this because the sample given produced the expected output and not the described bug (i.e. the infamous "works for me"), so will hope it's fixed with package updated. Feel free to open a new Issue if you are still having this trouble.
