### ISSUE TITLE
Client ctor can't find profile on Windows

### ISSUE THREAD

**Issue by swn1** [ipython/ipyparallel#201]
I manually configured a small test cluster using Azure vms and Anaconda 3, installed ipyparallel using conda, executed ipcontroller, copied the -engine file to the other machines and ran ipengine on them.

When I try to run the example script at the bottom of the readme here, I get an error that the default path to the client.json file is not valid.  Providing an explicit path doesn't work either.

After fiddling with it for a while I find that os.path.isdir works for the path components preceding ".ipython" and fail for that directory and (of course) anything under it.

Using the 8.3 filename for that directory doesn't seem to help.

**Comment by swn1** [comment]
I copied the json file to c:\ and used the explicit path parameter to the ctor, it worked as expected.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

Feel free to open a new Issue if you are still having this trouble.
