### ISSUE TITLE
Cannot import modules to remote engines hosts

### ISSUE THREAD

**Issue by d0pa** [ipython/ipyparallel#209]
All modules are installed on windows client and on linux nodes only installed ipyparallel v5.2.0 via pip install. Cluster working a OK, except when importing modules (own or such as numpy) error raised "No module named "module". Using Remote Imports raises same error.

Do I need to copy all modules manually to all engines (scp and set sys.path) or setup shared storage ?
Is there way to import modules to engines host via ipyparallel client only, with installation or copying of modules ?

Setup:
Node 0 - Controller + Engines (Linux)
Node 1-2 - Engines (Linux)
Node 3 - Client (Windows or Linux)

**Comment by minrk** [comment]
Yes, in general you need to have packages and modules installed on the remote machines to use them. Shared storage is the easiest way, but scp / rsync work, too.

You can send files with ipyparallel, but it there isn't a method provided by default. For instance this would send foo.py:

```python
def send_file(view, path):
    with open(path, 'rb') as f:
        data = f.read()
    def _write_file(path, data):
        with open(path, 'wb') as f:
            f.write(data)
    return view.apply(_write_file, path, data)
        
send_file(rc[0], 'foo.py')
```

**Comment by d0pa** [comment]
Thanks for a quick replay. If I understand correctly python script sent to engine will execute exactly same way as it is on a local machine, then what is use case for "view.sync_imports()" ?

**Comment by minrk** [comment]
> what is use case for "view.sync_imports()" ?

typing regular imports to execute them everywhere:

```python
with view.sync_imports():
    import numpy
    import scipy
```

will import numpy, scipy everywhere.

**Comment by d0pa** [comment]
Does it make sense, to "view.sync_import*()" make it work like rsync ?

**Comment by minrk** [comment]
I'm not sure what `view.sync_import*()` means, nor what it would mean for an import hook to work like rsync. `sync_imports` is a simple import hook that records imported modules, then executes the same imports on the engines.

**Comment by d0pa** [comment]
sorry for not being clear about what I mean, would it be easy for a user to call function something like view.sync_engine() and all files from a client working directory would be rsync'd to all engines ?

**Comment by minrk** [comment]
Ah, I see. You could implement such a function. [Here is a prototype](https://nbviewer.jupyter.org/gist/minrk/c48a05adf8ea04c4b201f25f3405745f) of such an rsync implementation.

**Comment by d0pa** [comment]
Thank you very much !
