### ISSUE TITLE
New Interface: HTML interface to the DB backend

### ISSUE THREAD

**Issue by arita37** [ipython/ipyparallel#210]
Similar to Flower for Celeri Scheduler, it would useful and easy to have a small HTML interface  for tasks: 
   
   1) Not Yet Run Tasks
   2) Running Tasks
   3) Finished Tasks

Example here:
https://github.com/mher/flower

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Closing as duplicate of #137
