### ISSUE TITLE
Engines exit after several operations (ZMQ and QT5 headless event loop problem?)

### ISSUE THREAD

**Issue by histed** [ipython/ipyparallel#213]
I am running several engines on a SLURM cluster.  Engines were exiting unexpectedly after a few apply_async() calls with log errors as below:

````
2016-12-17 22:52:04.733 [IPEngineApp] Importing canning map
2016-12-17 22:52:04.736 [IPEngineApp] entering eventloop <function loop_qt5 at 0x2aaadf7e9ed8>
QXcbConnection: Could not connect to display
srun: error: : task 0: Aborted
````

I thought this might be because the QT5 event loop was looking for a display and the cluster nodes are headless.  To the engine environments I added:

````
export QT_QPA_PLATFORM=offscreen
````

And now the engines seem to stay alive.  I haven't done a ton of testing, however.

````
# packages in environment 
#
ipyparallel               5.2.0                    py27_0
pyqt                      5.6.0                    py27_0
pyzmq                     15.4.0                   py27_0
````

**Comment by minrk** [comment]
That sounds like a C-level exit happening in Qt due to the failure to connect to the display. It seems like you have a fix, too. Thanks for posting that! Is there anything else that you think should be done?

**Comment by histed** [comment]
Hi Min,

This is with a recent version of anaconda, so it seems like this problem has the potential to bite a large number of anaconda users. 
An update to the docs seems important, but I wonder if it makes sense to change the ipengine code such that it requests a headless QT5 environment.  I don't see much downside as I think most ipengines will be running headless.  
Thanks.

**Comment by isaacovercast** [comment]
+1 This just bit me. I would second the idea to run engines in headless QT5 by default.

Alternatively, if it would at least be possible to somehow report engine failure more explicitly this would be helpful. Jobs run fine and report success, so to then find the engine dead is quite mysterious.

**Comment by histed** [comment]
Good to close?

**Comment by isaacovercast** [comment]
Fine with me. The workaround is fine, but i'm surprised this doesn't impact more people.

**Comment by alicedb2** [comment]
I ran into this problem several times in the past. The work-around above didn't fix the issue. It is just today that I was able to get rid of it. I use ``ipcluster`` on a headless server and as mentioned above by @histed the problem will usually pop-up when ``loop_qt5`` appears in a the debug output of the engines. In my case qt5 is called because my tasks use matplotlib to plot something.

The way to fix this when you're using matplotlib is to use Agg backend. Switching to this backend must happen before pyplot is imported, i.e. 

```
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
```

This workaround might not work when another library makes use of qt5.

**Comment by isaacovercast** [comment]
@alicedb2 Thanks for writing up the solution for this problem. I've run into this matplotlib Agg backend thing a bunch of times before and it can be very frustrating. Thanks for including the documentation here so others who run into this might make use of it in the future.
