### ISSUE TITLE
OSX: how do I remove ipyparallel?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [ipython/ipyparallel#215]
I've installed ipyparallel in the past but now I would like to remove it.

I've even deleted my anaconda folder and all the jupyter folders in OSX. Still even after a new install ipyparallel comes back - with errors as I've not installed the software.

i do I delete it permanently??

**Comment by minrk** [comment]
I'm not sure what you mean. `pip uninstall ipyparallel` or `conda remove ipyparallel` should remove it. If you are getting errors about the extension after uninstalling when you run the notebook, you may want to run:

    jupyter serverextension disable ipyparallel.nbextension
