### ISSUE TITLE
If task is running, how to forcing  shut down the engine?

### ISSUE THREAD

**Issue by httpservlet** [ipython/ipyparallel#216]
Client.shutdown need to wait for task to finish, and then shut down the engine
If task is running, how to forcing  shut down the engine?

**Comment by minrk** [comment]
Client.shutdown is a 'polite' shutdown. It sends a message to the engines and asks them to clean up and exit.

Until we have a nanny set up, forceful shutdown can't be done via public API. If you are using a local cluster, however, you can signal engines with `os.kill`.
