### ISSUE TITLE
cluster tab status "error starting cluster", '_xsrf' argument missing from POST

### ISSUE THREAD

**Issue by cekees** [ipython/ipyparallel#218]
When I try to start a cluster in the cluster tab (either the default or a custom MPI profile), I get "error starting gluster" in the  status column of the cluster tab. There is nothing in the .ipython/PROFILE/logs but on the host system running jupyter hub I get the following from `docker logs jupyter-username`:

`
[W 2017-01-05 20:47:24.098 cekees web:1545] 403 POST /user/cekees/clusters/default/start (173.235.23.125): '_xsrf' argument missing from POST
[W 2017-01-05 20:47:24.108 cekees log:47] 403 POST /user/cekees/clusters/default/start (173.235.23.125) 10.57ms referer=https://mistral.hrwallingford.com/user/cekees/tree?
`

The container is on hub.docker.com at erdccm/proteus:latest, which is based on the design of jupyter/docker-stacks. I've verified that the container and cluster tab works fine as jupyter notebook server. 

Python3 on the host: 

`
python3 -c "import IPython; print(IPython.sys_info())"
{'commit_hash': '5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.4/dist-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Linux-3.16.0-4-amd64-x86_64-with-debian-8.6',
 'sys_executable': '/usr/bin/python3',
 'sys_platform': 'linux',
 'sys_version': '3.4.2 (default, Oct  8 2014, 10:45:20) \n[GCC 4.9.1]'}
`

Python2 in the container:

`python -c "import IPython; print(IPython.sys_info())"
{'commit_hash': u'5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/jovyan/.hashdist/bld/ipython/4bv6wg7xr2k6/lib/python2.7/site-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Linux-3.16.0-4-amd64-x86_64-with-debian-8.6',
 'sys_executable': '/home/jovyan/proteus/linux2/bin/python2.7',
 'sys_platform': 'linux2',
 'sys_version': '2.7.11 (default, Dec  2 2016, 00:17:24) \n[GCC 4.9.2]'}
`

**Comment by thoth291** [comment]
I strongly believe this need to be reopened.
I'm using latest available notebook and jupyter cluster on my linux.
Then I start a `jupyter notebook` with `open_browser=Flase` and `NotebookApp.password=sha1:xxx` (as well as `certfile` and `keyfile`).
Then connect to it from my **Windows** and go to my cluster tab: where I get this:
![image](https://cloud.githubusercontent.com/assets/2971670/24928850/7ec91ad6-1ec9-11e7-98ef-32edec40b073.png)

And this on my linux side:
```bash
[W 15:15:32.456 NotebookApp] 403 POST /clusters/default/start (111.111.91.11): '_xsrf' argument missing from POST
[W 15:15:32.461 NotebookApp] 403 POST /clusters/default/start (111.111.91.11) 6.66ms referer=https://machinehostname.domain.com:8889/tree?
```

Here is the status of my packages:
```bash
notebook                  5.0.0                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter-c-kernel          1.0.0                     <pip>
jupyter-dashboards        0.6.1                     <pip>
jupyter_client            4.3.0                    py27_0    defaults
jupyter_console           5.0.0                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
jupyterlab                0.2.0                     <pip>
ipyparallel               6.0.2                    py27_0    defaults
```

Please please help!
Non of my team members can use my notebooks anymore (without messing with manual cluster start which we have tried to avoid using Cluster Tab in the first place).

**Comment by parashardhapola** [comment]
I have the same issue. I'm trying to use 'IPython Clusters' tab and on pressing start it shows 'error starting cluster' under status column.

    [I 14:46:50.473 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
    [W 14:46:51.473 NotebookApp] Could not find Zotero citation styles directory.
    [I 14:46:51.571 NotebookApp] Loading IPython parallel extension
    [I 14:46:51.643 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.4
    [I 14:46:51.986 NotebookApp] [nb_anacondacloud] enabled
    [I 14:46:52.001 NotebookApp] [nb_conda] enabled
    [I 14:46:52.188 NotebookApp] ✓ nbpresent HTML export ENABLED
    [W 14:46:52.188 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
    [I 14:46:52.201 NotebookApp] Serving notebooks from local directory: /home/parashar
    [I 14:46:52.201 NotebookApp] 0 active kernels 
    [I 14:46:52.201 NotebookApp] The Jupyter Notebook is running at: http://localhost:29090/
    [I 14:46:52.201 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    [W 14:46:53.712 NotebookApp] 404 GET /api/kernels/22308abd-6e6e-4911-ae56-8cfd05211b05/channels?session_id=298C932D930A4C24A38E152DD24C20EC (::1): Kernel does not exist: 22308abd-6e6e-4911-ae56-8cfd05211b05
    [W 14:46:53.772 NotebookApp] 404 GET /api/kernels/22308abd-6e6e-4911-ae56-8cfd05211b05/channels?session_id=298C932D930A4C24A38E152DD24C20EC (::1) 77.28ms referer=None
    [W 14:47:02.703 NotebookApp] Replacing stale connection: 22308abd-6e6e-4911-ae56-8cfd05211b05:298C932D930A4C24A38E152DD24C20EC
    [W 14:47:06.028 NotebookApp] 403 POST /clusters/default/start (::1): '_xsrf' argument missing from POST
    [W 14:47:06.032 NotebookApp] 403 POST /clusters/default/start (::1) 5.34ms referer=http://192.168.25.5:39090/tree/scratch/quadcomb/scripts

**Comment by damianavila** [comment]
@minrk I am seeing this as well on other extensions even using `utils.ajax` or the code published in your blog post... any idea what could be happening here?

**Comment by minrk** [comment]
I've double-checked and verified that this does indeed work with current versions of ipyparallel and notebook. My guess is that old javascript is being served somehow (i.e. the js extension isn't getting updated, or old js is still present).

If you check `http://localhost:8888/nbextensions/ipyparallel/clusterlist.js` (or wherever your notebook server is), you should see a line like this:

```javascript
    // use base utils.ajax in notebook >= 4.3
    // for xsrf settings, etc.
    var ajax = utils.ajax || $.ajax;
```

If you don't, then it's using the old javascript.

If this is Linux, you might check for `ipyparallel` in  `~/.local/jupyter/share/nbextensions` or `~/Library/Jupyter/nbextensions`. If it's present, remove it, either by hand or with `jupyter nbextension uninstall ipyparallel`.

**Comment by thoth291** [comment]
Hi, @minrk 
You were right - I had local copy of the JS in my `~/.local` so I deleted it and reinstalled ipyparallel (reinitialized the extensions as well).

But I still get the same error:
```bash
[I 11:37:50.693 NotebookApp] 302 GET /api/sessions?_=1492533258380 (149.178.91.11) 3.98ms
[I 11:37:50.697 NotebookApp] 302 GET /api/terminals?_=1492533258381 (149.178.91.11) 2.09ms
[I 11:38:33.092 NotebookApp] 302 GET /api/sessions?_=1492533258382 (149.178.91.11) 2.37ms
[I 11:38:33.096 NotebookApp] 302 GET /api/terminals?_=1492533258383 (149.178.91.11) 1.81ms
[W 11:38:45.836 NotebookApp] 403 POST /clusters/mpi/start (149.178.91.11): '_xsrf' argument missing from POST
[W 11:38:45.851 NotebookApp] 403 POST /clusters/mpi/start (149.178.91.11) 16.55ms referer=https://linuxhostname:8888/tree
[I 11:38:56.722 NotebookApp] 302 GET /api/sessions?_=1492533258384 (149.178.91.11) 2.39ms
[I 11:38:56.726 NotebookApp] 302 GET /api/terminals?_=1492533258385 (149.178.91.11) 1.96ms
[I 11:39:25.312 NotebookApp] 302 GET /api/sessions?_=1492533258386 (149.178.91.11) 1.19ms
[I 11:39:25.314 NotebookApp] 302 GET /api/terminals?_=1492533258387 (149.178.91.11) 0.78ms
```

Here is my JS file which I'm getting on my notebook:
```javascript
// Copyright (c) Jupyter Development Team.
// Distributed under the terms of the Modified BSD License.

define([
    'base/js/namespace',
    'jquery',
    'base/js/utils',
], function(IPython, $, utils) {
    "use strict";

    // use base utils.ajax in notebook >= 4.3
    // for xsrf settings, etc.
    var ajax = utils.ajax || $.ajax;
```
Full file is attached [here: clusterlist(3).js.txt](https://github.com/ipython/ipyparallel/files/930450/clusterlist.3.js.txt)

So what is wrong now?

**Comment by parashardhapola** [comment]
Deleted '~/.local/share/jupyter/nbextensions' directory.
Reinstalled ipyparallel
Reinstalled jupyter
Reinstalled jupyter_contrib_nbextensions

It works now!

**Comment by thoth291** [comment]
Thank you, @parashardhapola .
Indeed, once I reinstalled them all together (uninstalled and then installed) - it started to work!
Thanks to both of you!

**Comment by jonathanng** [comment]
If you're on Windows, delete everything in 'Users\Administrator\AppData\Roaming\jupyter\nbextensions'
