### ISSUE TITLE
how to reliably start python2 from profile in cluster tab

### ISSUE THREAD

**Issue by cekees** [ipython/ipyparallel#221]
When I start a cluster from the cluster tab the engines are using python3. This may be more appropriate as a jupyterhub issue... @minrk you helped me fixed this about a year ago, but the problem seems to be back. The fix before, which seems to no longer work around the issue, is modifyng the ipython profile like so:

```
    echo "c.LocalControllerLauncher.controller_cmd = ['python2', '-m', 'ipyparallel.controller']\nc.LocalEngineSetLauncher.engine_cmd = ['python2', '-m', 'ipyparallel.engine']\n" \
          >> /home/$NB_USER/.ipython/profile_mpi/ipcluster_config.py
```

I verified that I get python2 engines if I open a terminado terminal and run `ipcluster -n 4 --profile="mpi"`, and if I use the same container for a tmpnb instance instead of as jupyterhub.   When I use the jupyterhub cluster tab I get 4 python2 processes and 4 python3 processes whereas in the other scenarios I get 8 python2 processes.

You should have access to the same single-user setup via try.proteustoolkit.org:8000, which has a working cluster tab. I can add you to the jupyterhub system if that would help.

**Comment by minrk** [comment]
Is it the controller or the engine that's not seeing your config? I would guess it's the engines, not the controller.

This config will be correct for 'Local' controller/engines, but that doesn't affect the MPIEngineSetLauncher, so replace `LocalEngineSetLauncher` with `MPIEngineSetLauncher`

If you want to set more globally, try using `EngineMixin` instead, which will affect all launchers:

```python
c.ControllerMixin.controller_cmd = ['python2', '-m', 'ipyparallel.controller']
c.EngineMixin.engine_cmd = ['python2', '-m', 'ipyparallel.engine']
```

**Comment by cekees** [comment]
Yes, it was the engines. replacing with MPIEngineSetLauncher works. I'll keep the EngineMixin in mind. Thanks!
