### ISSUE TITLE
scripts subdir missing in pypi sources

### ISSUE THREAD

**Issue by marbre** [ipython/ipyparallel#230]
I noticed that the scripts subdirectory is missing in the pypi tarball. Thus the `console_scripts` are not installed. The tarball I can get from github is fine. However, for Gentoo Linux, we normally download the sources from pypi.

**Comment by minrk** [comment]
Weird, I must have done something when I uploaded. I'll do some testing and make a new release.

**Comment by minrk** [comment]
Uploaded 6.0.2 correctly.
