### ISSUE TITLE
Unable to use AsyncMapResult when *some* of the tasks have raised an exception.

### ISSUE THREAD

**Issue by ksze** [ipython/ipyparallel#234]
I'm running into some problem when using ipyparallel: when *some* of the tasks raise an exception, there seems no way to get at the successful task results in the AsyncMapResult.

I have posted the same question on StackOverflow, along with some minimal sample code to reproduce the issue: https://stackoverflow.com/questions/42570660/iterate-through-asyncmapresult-where-some-tasks-have-raised-an-exception

Versions:
- Python 2.7.9
- ipython==5.2.2
- ipyparallel==6.0.1

**Comment by xavieran** [comment]
I'm running into the same issue. As a workaround I try:except: everything within my tasks and then return the exception. Would be really interested in a fix for this though.

**Comment by minrk** [comment]
Matching the return_exceptions argument of [asyncio.gather](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather) is quite sensible!
