### ISSUE TITLE
Clarification for the intended default for the task DB

### ISSUE THREAD

**Issue by lintusj1** [ipython/ipyparallel#242]
Hi,

I was reading through the documentation regarding the task DB after I noticed that starting a local cluster with `ipcluster start -n 4` actually uses the `DictDB` on the hub. Reading from [here](http://ipyparallel.readthedocs.io/en/latest/db.html) gave an impression that it should be disabled by default (which I think would be better)

> This database behavior is optional due to its potential Cost, so you must enable one...

But then in [here](http://ipyparallel.readthedocs.io/en/latest/process.html#database-backend) it says that the `DictDB` would be the default (found in the comments of the code snippet):

> This is the default and the fastest...

Which way should it be? Would there be perhaps a chance for a command line argument for the `ipcluster` to control that?

**Comment by minrk** [comment]
> Which way should it be?

The docs need to be updated. It was off by default for some early versions, but DictDB was enabled by default when it gained the ability to limit its size by culling old tasks, so there should be little reason to use `--nodb` anymore, I think.

> Would there be perhaps a chance for a command line argument for the ipcluster to control that?

It is an argument to ipcontroller, e.g. `--nodb` or `--dictdb` or `--sqlitedb`. In general, controller arguments aren't exposed at the `ipcluster` CLI, but you can set them in your config files: either in `ipcontroller_config`, or set controller args in the Launcher config in ipcluster_config.py, depending on which Launcher you use.

It might be possible to pass through controller arguments in `ipcluster start`. I'll look into that. It will probably look like:

    ipcluster start -- --controller-args --go-here

e.g.

    ipcluster start -- --nodb

**Comment by minrk** [comment]
#244 should enable passing through controller args from `ipcluster start -- ...`

**Comment by lintusj1** [comment]
This is very good, thank you!
