### ISSUE TITLE
Why doesn't the interactive decorator work with functions that have closures?

### ISSUE THREAD

**Issue by rueberger** [ipython/ipyparallel#248]
# Context

I'm using ipyparallel to distribute GPU jobs. Each host in the cluster has the same number of engines as it has GPUs, the idea being that each engine corresponds to a GPU. 

I want to map a function like

```
def foo(x, device):
    ...
```

where `device` specifies the GPU `foo` runs on. 

Device allocations are made explicitly, and pushed to the corresponding engines:

```
rc = Client(profile='gpu_prof')

# len(rc) == len(device_allocations)
# defined such that the tuple (hostname, device) is unique for each engine
device_allocations = [...]

for engine_id, engine_device in enumerate (device_allocations): 
    rc[engine_id].push({"device": engine_device})
```

with the idea being that the map would be expressed as something like

```
@interactive
def foo_helper(x):
    return foo(x, device=device)

rc[:].map(foo_helper, x_list)
```

But before map has a chance, interactive throws `TypeError: arg 5 (closure) must be tuple` for foo_helper in this case somehow has a closure (according to the interpreter). 

It is probably important to note that in this case `foo` is defined in a separate module. I have not been able to replicate this interactively (when defined interactively `foo_helper` does not have closures) - I don't understand why. 

which brings me to my question... 

# Question

Why does `interactive` require that wrapped functions have no closures? Surely there's a good reason?  I would be more specific but I fear I'm getting out of my depth python-internals-wises so I'll leave it at that... 

I tried many different things to try to get this to work (map some `foo_helper` where the device kwarg gets assigned to whatever the engine's value for `device` is), and the only way I've been able to get it to work is by writing my own version of `interactive` that will wrap functions with closures. 

# Alternative Question

 Being not so familiar with ipyparallel, it's totally possible I'm trying to solve this problem in a completely dumb way. What's the recommended approach for this sort of thing?

Any and all feedback greatly appreciated!

**Comment by minrk** [comment]
> Why does interactive require that wrapped functions have no closures? Surely there's a good reason? 

Because stdlib pickle doesn't support closures. If you use cloudpickle or dill, functions with closures can be sent:

    rc.use_cloudpickle()


> It is probably important to note that in this case foo is defined in a separate module.

That is generally important. Are `foo` and `foo_helper` both defined in this module?

When decorating a function with `@interactive`, it is trying to detach from the module in which it is defined (i.e. accessing `foo` in module globals will not work). So it cannot rely on *any* names defined in the surrounding module. If `foo` is defined in that module, `foo_helper` must `import foo` inside the function, in order to find it:

```python
@interactive
def foo_helper(x):
    from mymodule import foo
    return foo(x, device) # device will be looked up in the interactive namespace
```

Another way to do this without relying on `@interactive` is to pass arguments that live on the engines as References:

```python
def foo_helper(x, device):
    return foo(x, device)

rc[:].map(foo_helper, x_list, [ipp.Reference('device')] * len(x_list))
```

**Comment by rueberger** [comment]
This is very helpful, thanks! `foo` and `foo_helper` are generally not defined in the same module.  Going to go with the `Reference` method as that seems to be far and away the most elegant.
