### ISSUE TITLE
Shared read-only access to arbitrary objects?

### ISSUE THREAD

**Issue by wmayner** [ipython/ipyparallel#250]
Is it possible for several engines to share read-only access to a single copy of an arbitrary object? And if so, how?

Sorry if this is answered in the documentation—I checked [here](http://ipyparallel.readthedocs.io/en/latest/details.html?highlight=copy#non-copying-sends-and-numpy-arrays), and the following paragraph seems to imply this is possible under certain circumstances:
> If you have an object that provides a Python buffer interface, then you can always send that buffer without copying - and reconstruct the object on the other side in your own code. It is possible that the object reconstruction will become extensible, so you can add your own non-copying types, but this does not yet exist.

But I'm afraid I don't really understand how this would work.

**Comment by minrk** [comment]
This would have to be done at the library level, not in IPython parallel. The text you quoted should be clarified. The zero-copy is that it's not producing extra copies in memory for serialization. It's not a shared memory object.

[This notebook](https://github.com/jupyter/ngcm-tutorial/blob/524ea8065de366c6e7f04121718cb96c0ed139c5/Part-3/examples/memmap.ipynb), for example, uses `numpy.memmap` to create shared arrays.

**Comment by wmayner** [comment]
Gotcha, thanks!
