### ISSUE TITLE
Setting IPyParallel Cluster Tab to spawn mpi workers on variable at runtime machine list

### ISSUE THREAD

**Issue by thoth291** [ipython/ipyparallel#256]
I have access to 10 machines - each of them have 60 cores.
Other users using it too - so I don't want to abuse shared resource and distribute my workers more or less evenly using this rule:
1. If number of requested engines <= 30 create them on one random machine
2. If number of engines > 30 then count how many machines you might need and then pick them randomly and create the engines.
```For example: If I had requested 200 engines then I'll need ceil(200/30)=7 machines; then I start 30 engines on random 6 of them and rest 20 engines start on the last random machine.```
3. Minor note: I will never requested more than 300 engines

### I wonder if I can put this logic somewhere and make a special profile which will handle that.
One comment: when I lunch the engines I'll use `mpirun` with appropriate `np` and `perhost` parameters and my ipcontroller will be on one of the machines.

All what I need is a good example - I can code the logic myself...

Thank you very much for your help!

**Comment by minrk** [comment]
Probably the best way to do this would be with an MPI hostfile to tell mpi where to allocate jobs.

**Comment by thoth291** [comment]
Yeah - I tried to setup a profile like that and replace mpiexec with my mpiexec which does the math and spawns mpiexec after that - but that was not working... Will investigate it later....

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.
