### ISSUE TITLE
Exception when using MPI with %autopx

### ISSUE THREAD

**Issue by GregDMeyer** [ipython/ipyparallel#257]
Hi,
I am using MPI engines with ipyparallel. When I use `%autopx`, the following exception occurs whenever I run a cell:

<code>
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/greg/Dropbox/Berkeley_lab/dynamite/.venv/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/greg/Dropbox/Berkeley_lab/dynamite/.venv/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/greg/Dropbox/Berkeley_lab/dynamite/.venv/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 200, in do_execute
    if res.error_before_exec is not None:
AttributeError: 'bool' object has no attribute 'error_before_exec'
</code>

From a preliminary glance at the source, it looks like `shell.run_cell()` is returning a `bool` in this case for some reason. When I run each line with `%px`, there is no problem.

I can dig deeper at some point, but wanted to raise the issue.

Cheers

**Comment by minrk** [comment]
@GregDMeyer what's `pip list`? It may be that the `IPython` package is a bit out of date.

**Comment by GregDMeyer** [comment]
Thanks! I just made sure to upgrade everything but I still have the same issue. `pip list` has
```
ipykernel (4.6.1)
ipyparallel (6.0.2)
ipython (6.0.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
```

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I believe this issue is resolved by using up-to-date versions of all ipython packages.

Feel free to open a new Issue if you are still having this trouble.
