### ISSUE TITLE
ipyparallel.nbextension doesn't work in Jupyterhub

### ISSUE THREAD

**Issue by basnijholt** [ipython/ipyparallel#27]
I've added `c.NotebookApp.server_extensions.append('ipyparallel.nbextension')` to the `jupyterhub_config.py` but the cluster tap doesn't show up.

Tried latest master version of Jupyterhub and ipyparallel.

EDIT:

I've noticed that it does work when I add the line in `/home/bnijholt/.jupyter/jupyter_notebook_config.py`, but the tab shows up without any options when I add it in `/etc/ipython/ipython_config.py`.

EDIT 2:

I fixed it by making a config in `/etc/jupyter/jupyter_notebook_config.py`.

There will be others with similar problems that have defined kernels and engines as in http://stackoverflow.com/questions/29773954/change-ipython-3-for-python-3-kernel-to-python2-for-the-cluster-too/29798906#29798906

**Comment by minrk** [comment]
jupyterhub_config.py only configures the Hub application. It does not affect notebook servers. I see you've discovered the right place for the configuration is jupyter_notebook_config.py.
