### ISSUE TITLE
Feature request: exit engine if time remaining < min required to process a task

### ISSUE THREAD

**Issue by rjplevin** [ipython/ipyparallel#277]
I'm using ipyparallel to run Monte Carlo simulations for a model that runs for ~10 min. When running on a cluster, it's wasteful of resources to start another run on an engine that has less than 10 min left before its "walltime" expires and the process is killed by the job scheduler.

I'd like to be able to specify options to engines that indicate (i) the amount of "walltime" allocated for the job, (ii) the minimum amount of time remaining below which the engine should shutdown. 

I imagine this is not an uncommon case for users working on clusters.

**Comment by minrk** [comment]
This should be doable with the existing dependency functionality. First, you will need to record the wall-time somewhere on your engine. What I would do is this:

1. on the engine, discover the job time limit at startup, and store a deadline in the engine
2. use functional dependencies to reject tasks that are expected to finish after the deadline.

It would look something like this:

use `time.monotonic() + wall_time` to set a deadline and store it in your engine:

```python
# in ipengine_config.py
c.IPEngineApp.startup_command = """
import time
# discover wall time from environment somehow
JOB_DEADLINE = time.monotonic() + int(os.environ.get('WALL_SECONDS') or 300)
"""
```

and decorate your tasks with `@ipp.depend` to avoid running anywhere there isn't enough time left:

```python
import ipyparallel as ipp

def check_time_remaining(seconds):
    """Return true if there's at least `seconds` before JOB_DEADLINE"""
    import time
    return time.monotonic() + seconds < JOB_DEADLINE

# require ten minutes
@ipp.depend(check_time_remaining, 10 * 60)
def task(*args):
    do_stuff()

v.map(task, ...)
```

Here's a [complete notebook](https://nbviewer.jupyter.org/gist/minrk/9ecbad577afaf3b21d301ca80572ee86) that illustrates how it works. The only thing missing is retrieving the deadline from the environment, which will depend on how PBS communicates that.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.
