### ISSUE TITLE
In PBS-mode, why should we run `ipcontroller` on a node, multiple times?

### ISSUE THREAD

**Issue by kostrykin** [ipython/ipyparallel#278]
I'm currently reading myself into IPyParallel in PBS mode. The [documentation](https://ipyparallel.readthedocs.io/en/latest/process.html#using-ipcluster-in-pbs-mode) suggests to run the controller (`ipcontroller`) with the directive `#PBS -l nodes=1:ppn=4`, but it doesn't explain its purpose:

  1. What is the benefit of running `ipcontroller` on a node over running it locally?
  2. Why should one spawn it 4 times (`pbs=4`) and not just once?

To my understanding, the controller's task is to coordinate the engines and to "talk" to the client.

What am I missing?

**Comment by Seb-Leb** [comment]
I'd also like to know, I pent too much time trying to make this work on our cluster. When I ran the controller with PBS, the json files where not created in the profile/security directory, so I couldn't connect the client to it. When I ran the controller locally and the engines through PBS, it looked like everything connected well, but when I connected with the client, I couldn't see the engines. I am not sure what I am doing wrong, my guess is that its probably my PBS batch script. Now I think I might try dask distributed...

**Comment by jusjusjus** [comment]
So, I had a similar issue on our cluster.  I talked to the sys admin and he said that comm btw the submission node and the cluster nodes is blocked.  There are two ways out:
- If ssh is not completely blocked you can try to port forward each node to where your client is.  This should be also possible from the config file, but I wasn't able to figure out how.
- The second option is to have the controller run on the cluster and submit a client job to connect to it on the cluster.
Both are a bit ugly.  Talk to your sys admin.

**Comment by kostrykin** [comment]
@jusjusjus Thanks, this answers my first question, so it appears to be specific to the cluster-architecture. But what is with my second question: What is the purpose of running the controller more than once?

**Comment by minrk** [comment]
@kostrykin I generally prefer running the controller outside the cluster if networking allows it, but it's not always allowed. There can be performance benefits of having everything on work nodes, but the main reason, for me, is that it's often the only option.

The answer to question 2 is simple: it's a typo! The controller should only be run once.

@Seb-Leb dask-distributed is great! I highly recommend it. The most common issue when launching ipyparallel on a distributed system is getting the networking set up. You need to tell the controller to listen on an ip address that the work nodes can connect to, and you need to make sure that the engines don't start long before your controller starts.

To tell your controller to listen on en0 (the right interface for your network may vary):

```python
# ipcontroller_config.py
import netifaces
# this is: get the ipv4 address of en0
# you may want en2, etc.
# netifaces.interfaces() shows you all the interfaces available
en0 = netifaces.ifaddresses('en0')
c.HubFactory.ip = en0[netifaces.AF_INET][0]['addr']
```
