### ISSUE TITLE
Using ipyparallel in PBS-mode consumed a large amount of virtual memory in the submission node

### ISSUE THREAD

**Issue by cskyan** [ipython/ipyparallel#279]
Today the cluster administrator called me and said my running programs (ipcontroller and ipengine) were slowing the whole system. The memory usage of the process pbs_server which is used to manage the job submission kept increasing when I submitted the ipyparallel jobs.

What should I do to avoid this kind of issue? Is it a bug in ipyparallel?

If I use multiprocess module to parallelize my job, each process may also need 5GB memory. Is it because my split jobs are too coarse and the ipcontroller need to carry all the memory usage of each split jobs so that it slows down the job submission system? Or is it because zeromq has communication with pbs_server and the split jobs queued in zeromq would also make the pbs_server consuming the corresponding amount of memory?

**Comment by jusjusjus** [comment]
Maybe thie controller keeps a lot of computation results in memory that should be written to a file?  Can you send a minimal example?

**Comment by minrk** [comment]
If you tell the controller to use a database, it should spill things to disk instead of in memory:

```python
# ipcontroller_config.py
c.HubFactory.db_class = 'SQLiteDB'
```

If you aren't using delayed job retrieval, you can also disable the controller caching results entirely:

```python
c.HubFactory.db_class = 'NoDB'
```

which should keep memory usage down
