### ISSUE TITLE
ipcluster disappeared from 4.0.1

### ISSUE THREAD

**Issue by mhooreman** [ipython/ipyparallel#28]
Hello,

I've pip upgraded ipyparallel to 4.0.1 using python3 on ubuntu 14.04, and ipcluster command was not there anymore.

To be sure, I've pip installed back ipyparallel 4.0.0, and ipcluster command came back.

Can you fix this? It makes my system unusable...

Thanks a lot and best regards.

**Comment by minrk** [comment]
Sorry, dumb typo. I will release 4.0.2 with the fix shortly.

**Comment by mhooreman** [comment]
No problem Minrk, it can happen...

Thanks a lot!

**Comment by minrk** [comment]
4.0.2 is out.
