### ISSUE TITLE
IOError: Connection file '~/ .........ipcontroller-client.json' not found.

### ISSUE THREAD

**Issue by wang-jinghui** [ipython/ipyparallel#282]
I use anaconda,pip install ipyparallel
----------------------------------------------------------------------------------------
Waiting for connection file: ~/.ipython/profile_default/security/ipcontroller-client.json

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-1-3a46a487d861> in <module>()
      1 import ipyparallel as ipp
----> 2 c = ipp.Client()

**Comment by minrk** [comment]
Did you start a cluster with `ipcluster start`?

**Comment by wang-jinghui** [comment]
@minrk ,I do not know why it stopped，then there is the error message:'IOError........
 
![question1](https://user-images.githubusercontent.com/22521393/29236112-06d0c1f2-7f39-11e7-8241-b3778ae043ef.png)

![170812](https://user-images.githubusercontent.com/22521393/29236138-4d0c6a7c-7f39-11e7-8441-d67c9830c693.png)

**Comment by minrk** [comment]
I'm not sure how that path got created as a directory.  Try removing it and then starting the cluster again.

**Comment by wang-jinghui** [comment]
I am ready to reinstall
