### ISSUE TITLE
Additional template arguments in PBS

### ISSUE THREAD

**Issue by jusjusjus** [ipython/ipyparallel#283]
Hi,  i'm trying to add support for arbitrary arguments PBS template file, say other than `--n` and `--profile-dir`.  Would that make sense for you guys?  Is anyone interested in coaching me, that knows the ipython ecosystem well?

The idea would be to have a template file such as
`#PBS -l walltime={bar}
..
`
then to complete with a command
`ipcluster start --profile=foo --bar 12:00:01`
Thanks, jus

**Comment by minrk** [comment]
The best way, to me, is to provide a custom batch template via 

```python
c.PBSLauncher.batch_template = """
# your template here
"""
```

Then you can add whatever you like.

**Comment by jusjusjus** [comment]
Interesting.  That gives you potentially more control, but is it possible then to set the walltime on ipcluster start?

**Comment by minrk** [comment]
> but is it possible then to set the walltime on ipcluster start?

Not without some changes. Adding convenient CLI options isn't going to be easy, but you can always do things like `--MyLauncherClass.wall_time=00:10:00`, assuming your MyLauncherClass has a wall_time trait defined.

#285 adds a `BatchSpawner.namespace`, which you could use in combination with custom batch_template to load values from environment variables, enabling something like:

    WALLTIME=00:10:00 ipcluster start

with the config:

```python
# ipcluster_config.py
import os
c.PBSLauncher.batch_template = """
#!/usr/bin/env bash
#PBS -V
#PBS -N ipcontroller
#PBS -l walltime={wall_time}
ipengine --profile-dir="{profile_dir}" --cluster-id="{cluster_id}"
"""

c.PBSLauncher.namespace = {'wall_time': os.environ.get('WALLTIME') or '01:00:00'}
```

**Comment by jusjusjus** [comment]
Thanks, for my apps I can make it work that way.

This said, compared with the {n} syntax in the pbs template mechanism in
ipypar, your suggestions are a bit hacky.  I have some time to work on a
cleaner solution, say using dict insertion using format.  Would anyone be
interested in helping/mentoring?

**Comment by minrk** [comment]
Since the suggestion above with #285 is precisely adding user-specificed variables via the `{n}` syntax with `.format()`, I'm not sure what you are referring to as hacky compared to itself. You still have to provide both the dict of variables (`.namespace`) and the template that uses those variables (`.batch_template`).

If you have ideas for a cleaner solution, please feel free to open a pull request, or continue discussing ideas in this Issue.
