### ISSUE TITLE
recursive calls to `dview.map_sync` supported?

### ISSUE THREAD

**Issue by russelljjarvis** [ipython/ipyparallel#287]
In [SCOOP](https://github.com/soravux/scoop/) its possible to do futures `futures.map` on a function and a list inside a function that is already being evaluated with `futures.map`. I wonder if there is a way to achieve the same thing in ipyparallel?

**Comment by minrk** [comment]
This isn't possible at the moment because engines do not have the ability to submit new jobs. It should be possible with `dask`, which is what I would recommend these days for load-balanced execution in Python.

**Comment by russelljjarvis** [comment]
AOK thanks minrk
Also making a note for future reference to @rgerkin
