### ISSUE TITLE
Minor syntax error in docs

### ISSUE THREAD

**Issue by russelljjarvis** [ipython/ipyparallel#290]
https://github.com/ipython/ipyparallel/edit/master/docs/source/direct.rst#L93

People testing examples from direct view in the docs will find that one of the first examples doesn't work, since regular map needs to be cast to list in order to make the statement:

`serial_result == parallel_result` 
return True

The statement:
`serial_result = map(lambda x:x**10, range(32))`

should instead read:
`serial_result = list(map(lambda x:x**10, range(32)))`

**Comment by minrk** [comment]
Thanks! That sounds like the right fix. Would you like to make a PR?

**Comment by russelljjarvis** [comment]
AOK yes I will make a PR. Also is it okay if I add in some omitted import statements, that may not be obvious to a complete beginner?

**Comment by russelljjarvis** [comment]
done.
