### ISSUE TITLE
push/pull dont work with cloudpickle

### ISSUE THREAD

**Issue by dmacd** [ipython/ipyparallel#296]
Just hit the issue described here:
https://stackoverflow.com/questions/45626974/why-cant-ipyparallel-push-pull-when-using-cloudpickle

Repro locally:
![screenshot from 2017-10-27 16-56-05](https://user-images.githubusercontent.com/40836/32129030-09c2c73a-bb38-11e7-9602-b68b2b1161e4.png)

**Comment by russelljjarvis** [comment]
I also have this problem.
