### ISSUE TITLE
cannot connect to all started engines using PBS when n>100

### ISSUE THREAD

**Issue by basnijholt** [ipython/ipyparallel#301]
I start an ipcluster on a PBS cluster with a head node with:
```bash
ipcluster start -n 200 --profile=pbs
```
and wait until it tells me that the engines are successfully started.

Then I connect to the engines with:
```python
import ipyparallel
c = ipyparallel.Client(profile='pbs', timeout=120)  # timeout is needed otherwise it raises a `TimeoutError: Hub connection request timed out`
len(c)
```
`Out[10]: 32`

The results vary, sometimes I get lucky and all 200 engines are connected, but mostly not.

Starting 100 engines and connecting to them almost always works.

Could someone give me some handles on how to debug this?

## relevant ipython profile contents

`profile_pbs/ipcluster_config.py`:
```bash
c.IPClusterStart.controller_launcher_class = 'PBSControllerLauncher'
c.IPClusterEngines.engine_launcher_class = 'PBSEngineSetLauncher'
```

`profile_pbs/ipcontroller_config.py`:
```bash
c.HubFactory.ip = u'*'
```

**Comment by minrk** [comment]
It's almost certainly timeouts during registration. Increasing the engine registration timeout to several minutes ought to be . There are a few timeouts right now that can be relaxed (and probably should be significantly relaxed by default) when registration is taking a while. You can check the logs for the engine jobs and the controller job to see who is giving up on whom, which ought to tell you what timeouts are too short. The default values are probably too aggressively short, especially for a PBS context. My guess is that it's the engines that are giving up on the Hub, since the engines have the least patience.

```python
# ipengine_config.py
# how long engines should wait for connection files to arrive
# this is important if the controller might start significantly later than the engines
c.IPEngineApp.wait_for_url_file = 300
# how long the engine should wait for a registration response from the Hub
# this is significant if the Hub is under heavy registration load
c.EngineFactory.timeout = 300

# ipcontroller_config.py
# how long the Hub should wait for engines to begin responding to heartbeats.
# this could be sensitive to registration load as well.
c.HubFactory.registration_timeout = 600
```

**Comment by basnijholt** [comment]
That seems to solve the issues! Thanks a lot.

**Comment by basnijholt** [comment]
Currently, I am running code on a SLURM cluster with ~200 nodes of 32 cores.

Using the timeout suggestions you posted above I can start 1200 engines without any problem. All of them fire up and start in about 30 seconds after which `len(client)==1200`. This timing seems to independent of number of engines from `n=1` untill `n=1200`.

However, when trying to start more than 1200 cores, connects to some, for example `len(client)==500` and then after ~1 minute this number goes down.

Do you think there is still some other timeout/limit that prevents me from using that many cores?

(@georgwinkler is having this problem too)

**Comment by minrk** [comment]
It might be a little tricky, but do you have logs from when the engines go away? `ipcontroller --debug` produces a lot of output, especially with lots of engines, but it might be helpful to see exactly what's happening with the engines that stop. It's possible that if the heartbeat mechanism is too slow and if it can't process all of the heartbeats in the desired window it may think that heartbeats that are waiting to be handled are not going to come. The simplest solution if this is the case is to increase the heartbeat interval. The default is 30 seconds, try increasing it to a minute or two:

```python
# in milliseconds for some reason
c.HeartMonitor.period = 90000
```

The heartbeat period also influences registration time as engines only finish registering once they have responded to a heartbeat.

**Comment by minrk** [comment]
I've significantly changed how heartbeats work in #570, and am able to register 5000 engines without any failures with default parameters. I'm going to call this solved, but feel free to reopen if that, plus increasing HeartMonitor.period and IPController.registration_timeout don't work.

**Comment by basnijholt** [comment]
This is great! I am regularly using >30.000 cores on Azure, so I will give the new code a try soon(ish).
