### ISSUE TITLE
Can ipyparallel be used to run parallel scp sessions?

### ISSUE THREAD

**Issue by amadain17** [ipython/ipyparallel#302]
I'm looking to run multiple python scp sessions in parallel. I created a paramiko ssh session and used its transport in scp (from the SCPClient module) to scp files successfully from a remote machine to my local one. I wanted to parallelise this process. 

Here is the code I wanted to parallelize:

    dvScp = SCPClient(client.get_transport())
    import time
    p1=time.time()
    for file in result:
        print "Getting {}".format(file)
        dvScp.get(file, '.')
        print "Done"
    p2=time.time()
    print "scping took {} secs".format(p2-p1)
    client.close()

I ran into a raft of pickling issues which when I fixed one I was presented with another. So eventually I tried the following which stopped the pickling issues:

    %%px --local
    dvScp = SCPClient(client.get_transport())
    for file in result:
        #def dvscp(scpClientInst):
        #    scpClientInst.get(file, '.')
        dview.apply_async(dvScp.get, [file, '.'])```

but led to the following error:
    
    BadYieldError: yielded unknown object <MessageFuture at 0x10a850110 state=pending>

Is it possible to parallelize multiple scp sessions like this? All the examples I see for this module is for running arithmetic functions in parallel. If this is not the correct module can someone point me in the direction of the correct one?

**Comment by minrk** [comment]
Since this ought to be ~all IO, I would probably use a ThreadPoolExecutor. Then there ought to be no pickling or anything.
