### ISSUE TITLE
Engines that segfault aren't cleaned up properly

### ISSUE THREAD

**Issue by isaacovercast** [ipython/ipyparallel#322]
Hi folks,

First thanks for the really awesome work on ipyparallel, I love it very much.... Which is why i'm spending the time to report this bug in minute detail... FYI I have only tested this on the 5.x branch, so it may be fixed in 6.x. 

There's some housekeeping associated with segfaulting engines that's a little out of whack, I think. I can generate a segfault on a headless engine by importing matplotlib on the `5.x` branch, see for example https://github.com/messDiv/MESS/issues/2. Not sure how many other use cases this is impacting, but if segfaults generate this behavior then I'm sure it's cropping up at least here and there (cost me a ton of time to debug, so hopefully if we can nail it down it'll save some folks in the future).

Steps to reproduce:

Make a new file "wat.py" on a headless server (no $DISPLAY env variable):
```
import ipyparallel as ipp 
c = ipp.Client()
lbview = c.load_balanced_view()
def dobadstuff():
    import matplotlib.pyplot as plt
    plt.plot()
    return "wat {}".format(matplotlib.get_backend())
job = lbview.apply(dobadstuff)
try:
    job.result()
except:
    pass
c = ipp.Client()
print(c.ids)
print(c.queue_status())
```

At the command line run the following:
```
$ ipcluster start -n 4 --daemonize
$ ps -ef | grep "ipyparallel.engine" | grep -v grep | wc -l
4
```
Four engines running just fine. Now lets submit a job:
```
$ python wat.py
[0, 1, 2, 3]
{0: {u'queue': 0, u'completed': 1, u'tasks': 0}, 1: {u'queue': 0, u'completed': 0, u'tasks': 0}, 2: {u'queue': 0, u'completed': 0, u'tasks': 0}, 3: {u'queue': 0, u'completed': 0, u'tasks': 0}, u'unassigned': 0}
$ python wat.py
$ ps -ef | grep "ipyparallel.engine" | grep -v grep | wc -l
3
```
Oops, one engine died, but queue_status() isn't updated, as can be seen in the results of the next call to `wat.py`. Now again:
```
$python wat.py
[1, 2, 3]
{0: {u'queue': 0, u'completed': 1, u'tasks': 0}, 1: {u'queue': 0, u'completed': 0, u'tasks': 0}, 2: {u'queue': 0, u'completed': 1, u'tasks': 0}, 3: {u'queue': 0, u'completed': 0, u'tasks': 0}, u'unassigned': 0}
```
Now `c.ids` sees one id is dead, but 4 still remain in the `c.queue_status()`... and so on, until you run out of engines that haven't crashed, and then the `apply()` just hangs. `c.shutdown()` hangs as well, I assume because it's trying to shut down engines that have already died. 

I spent a __ton__ of time trying to debug this, hopefully i'm not just the stupid guy in the room. Had to enable debug mode in an engine with `ipengine --log-to-file --log-level=DEBUG`, but that seems like a pretty nasty thing to have to do.... Maybe there's a more graceful way to handle segfaults in engines?

**Comment by minrk** [comment]
I was able to reproduce this and fix it in #330.

When debugging, I find it much easier to use `ipcontroller` and `ipengine` directly, rather than ipcluster, since they log directly to the terminal.

What I tend to do:

    ipcontroller --debug &
    ipengine --debug &
    python wat.py

You can also use:

    ipcluster start --debug

which logs everything from all processes to the terminal in sufficiently recent ipyparallel versions.

I also used this handy, simpler segfaulting task, since I can't get matplotlib to segfault (this should usually be hard):

```python
def segfault():
    import ctypes
    libc = ctypes.CDLL('libc.so.6')
    libc.time(-1)  # segfault
```
