### ISSUE TITLE
Can't start engines from jupyterhub's "Ipython Clusters" tab

### ISSUE THREAD

**Issue by chenghuzi** [ipython/ipyparallel#323]
I installed ipyparallel from pip and followed the jupyterhub extension instruction from the readme of this repo. And the ipcluster could work in command line way. But When I try to start engine from the jupyterhub "Ipython Clusters" tab, I found I could not start engine from it:

<img width="1177" alt="screen shot 2018-04-13 at 13 56 43" src="https://user-images.githubusercontent.com/11160442/38719046-914be31c-3f22-11e8-8a0e-8d408082fc52.png">

Btw, no cluster will be shown in this tab even if I started engine.

I checked the source of this page and found that:

![screen shot 2018-04-13 at 13 59 03](https://user-images.githubusercontent.com/11160442/38719254-7edc5e7c-3f23-11e8-9d01-1e512b79ae83.jpg)

So, would it be possible this issue was caused by some extension problem?

My jupyterhub info:

    jupyter --version
    4.4.0
    ipyparallel (6.1.1)

**Comment by joelkim** [comment]
me tool.
cannot find a link to "http://localhost:8888/clusters?_=1527051154707"

current packages:
```
$ conda list jupyter
# packages in environment at /Users/user/anaconda3:
#
# Name                    Version                   Build  Channel
jupyter                   1.0.0            py36h598a6cc_0  
jupyter-contrib-core      0.3.3                     <pip>
jupyter-contrib-nbextensions 0.3.3                     <pip>
jupyter-highlight-selected-word 0.1.0                     <pip>
jupyter-latex-envs        1.3.8.4                   <pip>
jupyter-nbextensions-configurator 0.2.8                     <pip>
jupyter_client            5.2.2                    py36_0    anaconda
jupyter_console           5.2.0            py36hccf5b1c_1  
jupyter_core              4.4.0            py36h79cf704_0    anaconda
jupyterlab                0.30.6           py36h2f9c1c0_0  
jupyterlab_launcher       0.6.0                    py36_0  
$ conda list notebook
# packages in environment at /Users/user/anaconda3:
#
# Name                    Version                   Build  Channel
notebook                  5.4.0                    py36_0  
$ conda list nb
# packages in environment at /Users/user/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0  
_nb_ext_conf              0.4.0                    py36_1  
jupyter-contrib-nbextensions 0.3.3                     <pip>
jupyter-nbextensions-configurator 0.2.8                     <pip>
nb_anacondacloud          1.4.0                    py36_0  
nb_conda                  2.2.1            py36h349edbb_0  
nb_conda_kernels          2.1.0                    py36_0  
nbconvert                 5.3.1            py36h810822e_0    anaconda
nbformat                  4.4.0            py36h827af21_0    anaconda
nbpresent                 3.0.2            py36hef4c988_1  
nbsphinx                  0.2.18                    <pip>
widgetsnbextension        3.0.8            py36h34759f8_0  
```

**Comment by minrk** [comment]
The 404 on clusters suggests that the server extension is not enabled:

    jupyter serverextension enable --py ipyparallel

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

It looks like this issue is resolved.

Feel free to open a new Issue if you are still having this trouble.
