### ISSUE TITLE
Size limit for argument to `lbview.map_async` ?

### ISSUE THREAD

**Issue by michaelaye** [ipython/ipyparallel#324]
For a list of 40,022 path objects like these:

`PosixPath('/Volumes/Data/p4terrains/Meridiani_set_1_revised_CTX_List_part_1-1/B01_010011_1846_XI_04N358W/B01_010011_1846_XI_04N358W_0000.cub')`

the feedback system in the `results` object I get from `lbview.map_async` breaks down, when I use more than 40,003 paths, i.e. using `paths[:40004]` as input to the `map_async` call breaks (as in, results.progress does not get updated, but the processes are running as confirmed via `htop`), but `paths[:40003]` works fine.

The respective `sys.getsizeof()` byte sizes for these are 320096 and 320088.
Is this a known restriction in ipyparallel?

Note, that I had to downgrade tornado to 4.5 due the bugs discussed in #318.

**Comment by minrk** [comment]
Can you specify `chunksize=10` to chunk it into 4k tasks instead of 40k tasks? I'm not sure exactly what would be failing here.

**Comment by michaelaye** [comment]
On a different task, I had no communication again (`progress` attribute did not get updated) for a task list of length 27,603.
Using `chunksize=10` and no other changes made it work, thanks!
