### ISSUE TITLE
ipyparallel broken for tornado 4.5.3 ("RuntimeError: IOLoop is already running")

### ISSUE THREAD

**Issue by basnijholt** [ipython/ipyparallel#334]
I need to use `tornado` 4.5.3 because of this issue https://github.com/jupyter/notebook/issues/3397/

I tried to connect to an `ipycluster` and get the following error:

```
"RuntimeError: IOLoop is already running"
```

This problem was introduced quite recently because it was not present in 6.1.1.

Actually, I also tried installing https://github.com/ipython/ipykernel/pull/323 and https://github.com/ipython/ipython/pull/11155 with the new tornado, that that didn't help.

**Comment by minrk** [comment]
Probably an artifact of the tornado 5 support that messed something up with old tornado. Probably need to add a condition somewhere.

**Comment by minrk** [comment]
@basnijholt I think this is fixed by #337.

**Comment by minrk** [comment]
Released 6.2.2 with the fix
