### ISSUE TITLE
hang when doing remote call

### ISSUE THREAD

**Issue by DrTodd13** [ipython/ipyparallel#347]
```
import ipyparallel
cluster = ipyparallel.Client(profile='mpi')
dview = cluster[:]
@dview.remote(block=True)
def numba_test():
    import numba
    @numba.njit
    def f1(x):
        return x + 1
    return f1(7)
nt = numba_test()
```

This sequence will hang on the call to numba_test.  Any suggestions for debugging?  Is this expected to work?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

Sorry for not responding in a reasonable amount of time! It looks like this issue is resolved since it does not hang with current ipyparallel and numba.

Feel free to open a new Issue if you are still having this trouble.
