### ISSUE TITLE
AttributeError: module 'numpy' has no attribute '__version__' 

### ISSUE THREAD

**Issue by mehdiHadji** [ipython/ipyparallel#349]
am getting the following error message when I attempt to import pandas:

`import pandas`
AttributeError: module 'numpy' has no attribute '__version__'

Following is the full error message:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-9f8df34a69f4> in <module>
      1 import numpy
----> 2 import pandas
      3 
      4 
      5 print("hello")

C:\ProgramData\Anaconda3\lib\site-packages\pandas\__init__.py in <module>
     21 
     22 # numpy compat
---> 23 from pandas.compat.numpy import *
     24 
     25 try:

C:\ProgramData\Anaconda3\lib\site-packages\pandas\compat\numpy\__init__.py in <module>
      8 
      9 # numpy versioning
---> 10 _np_version = np.__version__
     11 _nlv = LooseVersion(_np_version)
     12 _np_version_under1p10 = _nlv < LooseVersion('1.10')

AttributeError: module 'numpy' has no attribute '__version__'`

**Comment by ressafri** [comment]
worked for me, thanks

**Comment by pintu4all** [comment]
Thank you very much. worked for me too

**Comment by ilyaas97** [comment]
This hasn't worked for me while running 'import Numpy as np', I as still getting the error 
AttributeError: module 'numpy' has no attribute '__version__'

**Comment by phenomenalDenzel** [comment]
This did not not also work for me on my pycharm. I am still getting the error
AttributeError: module 'numpy' has no attribute 'version'

**Comment by CapAllen** [comment]
Thx!

**Comment by Aakartion** [comment]
i have an error like this
AttributeError: module 'numpy' has no attribute 'zero'

**Comment by ravi7198** [comment]
still getting this
AttributeError: module 'numpy' has no attribute '__version__'

**Comment by nitindoodhiya** [comment]
problem solved with :

1 - pip uninstall -y numpy
2 - pip uninstall -y setuptools
3 - pip install setuptools or conda install setuptools
4 - pip install bumpy or conda install numpy
Any one will work. Conda/pip

**Comment by juanaranguren** [comment]
Guys, this is strange.
I'm getting the error "Importing the numpy c-extensions failed." when running a Pycharm project and the error is raised when app tries to import pandas.

This is kind of funny, coz I'm actually running Jupyter Notebook scripts that use pandas and imports it with no issues.
Any clues on how to solve this will be more than welcome.

**Comment by Navjot-Kaur-DA** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-6-c648e9a714b4> in <module>
      1 reg_with_pvalues = LinearRegression()
----> 2 reg_with_pvalues.fit(x,y)

<ipython-input-5-cd8a83994e84> in fit(self, X, y, n_jobs)
     12         sse = np.sum((self.predict(X)- y) ** 2, axis = 0) / float(X.shape[0]-X.shape[1])
     13 
---> 14         se = np.array([np.sqrt(np.diagnol(sse*np.linalg.inv(np.dot(X.T,X))))])
     15 
     16         self.t = self.coef_/se

~\anaconda3\lib\site-packages\numpy\__init__.py in __getattr__(attr)
    218             else:
    219                 raise AttributeError("module {!r} has no attribute "
--> 220                                      "{!r}".format(__name__, attr))
    221 
    222         def __dir__():

AttributeError: module 'numpy' has no attribute 'diagnol'
[http://localhost:8888/notebooks/Desktop/Navjot/Data%20science%20course/Data%20science%20course%20udmey%202020/Part_5_Advanced_Statistical_Methods_(Machine_Learning)/S34_L217/How%20to%20properly%20includ%20the%20pvalue%20working.ipynb#](url)

**Comment by 07Agarg** [comment]
> problem solved with :
> 
> 1 - pip uninstall -y numpy
> 2 - pip uninstall -y setuptools
> 3 - pip install setuptools
> 4 - pip install numpy

Worked for me too. Thanks!

**Comment by sooothkful** [comment]
thx

**Comment by sooothkful** [comment]
thx

**Comment by prakhargurawa** [comment]
problem solved with :

1 - pip uninstall -y numpy
2 - pip uninstall -y setuptools
3 - pip install setuptools or conda install setuptools
4 - pip install bumpy or conda install numpy
Any one will work. Conda/pip


This solution worked!!

**Comment by LatLongCoder** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-3-0f6b1045be79> in <module>
----> 1 import pandas as pd
      2 data = pd.read_csv ("F:\python\csv")
      3 data

~\AppData\Roaming\Python\Python38\site-packages\pandas\__init__.py in <module>
     20 
     21 # numpy compat
---> 22 from pandas.compat.numpy import (
     23     _np_version_under1p14,
     24     _np_version_under1p15,

~\AppData\Roaming\Python\Python38\site-packages\pandas\compat\numpy\__init__.py in <module>
      7 
      8 # numpy versioning
----> 9 _np_version = np.__version__
     10 _nlv = LooseVersion(_np_version)
     11 _np_version_under1p14 = _nlv < LooseVersion("1.14")

AttributeError: module 'numpy' has no attribute '__version__'

**Comment by shivaavvari** [comment]
Thanks ! this still works for me
