### ISSUE TITLE
Ipcluster slow and using 99% of (Hyperthreading Included) CPU (Mac OS)

### ISSUE THREAD

**Issue by freedomtowin** [ipython/ipyparallel#357]
I have been using my new Mac OSX 10.14 to process batch jobs with ipyparallel. 

I have noticed that the clusters are using 100% of my total cpu including hyper threads. This issue seems to start with pyzmq v16 and ipyparallel >6.0.2. Also I'm assuming it corresponds to tornado in some way. The error message below is for when I downgrade to ipyparallel=6.0.2 with pyzmq=18.0.0. 

 The 'loop' trait of an IPClusterStart instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' (i.e. <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10f049d30>) was specified.

Broken with the following (new) packages:
appnope=0.1.0=py37_0
backcall=0.1.0=py37_0
blas=1.0=mkl
bleach=3.1.0=py37_0
ca-certificates=2019.1.23=0
certifi=2018.11.29=py37_0
dbus=1.13.6=h90a0687_0
decorator=4.3.2=py37_0
entrypoints=0.3=py37_0
expat=2.2.6=h0a44026_0
gettext=0.19.8.1=h15daf44_3
glib=2.56.2=hd9629dc_0
icu=58.2=h4b95b61_1
intel-openmp=2019.1=144
ipykernel=5.1.0=py37h39e3cac_0
ipyparallel=6.2.3=py37_0
ipython=7.3.0=py37h39e3cac_0
ipython_genutils=0.2.0=py37_0
jedi=0.13.3=py37_0
jinja2=2.10=py37_0
jpeg=9b=he5867d9_2
jsonschema=2.6.0=py37_0
jupyter_client=5.2.4=py37_0
jupyter_core=4.4.0=py37_0
kernelml=2.657=pypi_0
libcxx=4.0.1=hcfea43d_1
libcxxabi=4.0.1=hcfea43d_1
libedit=3.1.20181209=hb402a30_0
libffi=3.2.1=h475c297_4
libgfortran=3.0.1=h93005f0_2
libiconv=1.15=hdd342a3_7
libpng=1.6.36=ha441bb4_0
libsodium=1.0.16=h3efe00b_0
markupsafe=1.1.1=py37h1de35cc_0
mistune=0.8.4=py37h1de35cc_0
mkl=2019.1=144
mkl_fft=1.0.10=py37h5e564d8_0
mkl_random=1.0.2=py37h27c97d8_0
nbconvert=5.3.1=py37_0
nbformat=4.4.0=py37_0
ncurses=6.1=h0a44026_1
notebook=5.7.4=py37_0
numpy=1.16.2=py37hacdab7b_0
numpy-base=1.16.2=py37h6575580_0
openssl=1.1.1b=h1de35cc_1
pandoc=2.2.3.2=0
pandocfilters=1.4.2=py37_1
parso=0.3.4=py37_0
pcre=8.42=h378b8a2_0
pexpect=4.6.0=py37_0
pickleshare=0.7.5=py37_0
pip=19.0.3=py37_0
prometheus_client=0.6.0=py37_0
prompt_toolkit=2.0.9=py37_0
ptyprocess=0.6.0=py37_0
pygments=2.3.1=py37_0
pyqt=5.9.2=py37h655552a_2
python=3.7.2=haf84260_0
python-dateutil=2.8.0=py37_0
pyzmq=18.0.0=py37h0a44026_0
qt=5.9.7=h468cd18_1
readline=7.0=h1de35cc_5
send2trash=1.5.0=py37_0
setuptools=40.8.0=py37_0
sip=4.19.8=py37h0a44026_0
six=1.12.0=py37_0
sqlite=3.26.0=ha441bb4_0
terminado=0.8.1=py37_1
testpath=0.4.2=py37_0
tk=8.6.8=ha441bb4_0
tornado=5.1.1=py37h1de35cc_0
traitlets=4.3.2=py37_0
wcwidth=0.1.7=py37_0
webencodings=0.5.1=py37_1
wheel=0.33.1=py37_0
xz=5.2.4=h1de35cc_4
zeromq=4.3.1=h0a44026_3
zlib=1.2.11=h1de35cc_3

**Working with the following (old) packages:
appnope=0.1.0=py35_0
blas=1.0=mkl
certifi=2018.4.16=py35_0
chest=0.2.3=py35_0
cloudpickle=0.2.1=py35_0
cycler=0.10.0=py35_0
cython=0.28.5=py35h0a44026_0
datashape=0.5.2=py35_0
decorator=4.0.10=py35_0
entrypoints=0.2.2=py35_0
freetype=2.5.5=1
futures-compat=1.0=py3_0
h5py=2.7.0=np111py35_0
hdf5=1.8.17=1
heapdict=1.0.0=py35_1
icu=54.1=0
ipykernel=4.6.1=py35_0
ipython=5.1.0=py35_0
ipython_genutils=0.1.0=py35_0
ipywidgets=6.0.0=py35_0
jbig=2.1=0
jinja2=2.8=py35_1
jpeg=8d=1
jsonschema=2.5.1=py35_0
jupyter=1.0.0=py35_3
jupyter_client=4.4.0=py35_0
jupyter_console=5.2.0=py35_0
jupyter_core=4.1.1=py35_0
libcxx=4.0.1=hcfea43d_1
libcxxabi=4.0.1=hcfea43d_1
libpng=1.6.27=0
libtiff=4.0.6=2
llvmlite=0.13.0=py35_0
locket=0.2.0=py35_1
markupsafe=0.23=py35_2
matplotlib=2.0.2=np111py35_0
mistune=0.7.2=py35_1
mkl=11.3.3=0
mock=2.0.0=py35_0
multipledispatch=0.4.8=py35_0
nbconvert=4.2.0=py35_0
nbformat=4.4.0=py35_0
ncurses=5.9=10
networkx=1.11=py35_0
nltk=3.2.2=py35_0
notebook=5.0.0=py35_0
numpy=1.11.1=py35_0
odo=0.4.2=py35_0
openssl=1.0.2h=2
pandas=0.18.1=np111py35_0
partd=0.3.6=py35_0
path.py=8.2.1=py35_0
patsy=0.4.1=py35_0
pexpect=4.0.1=py35_0
pickleshare=0.7.3=py35_0
pillow=3.3.1=py35_0
pip=9.0.1=py35_1
prompt_toolkit=1.0.3=py35_0
ptyprocess=0.5.1=py35_0
pygments=2.1.3=py35_0
pymysql=0.7.9=py35_0
pyparsing=2.1.4=py35_0
pyqt=5.6.0=py35_2
python-dateutil=2.6.1=py35_0
python.app=1.2=py35_4
pytz=2016.6.1=py35_0
pyyaml=3.11=py35_4
pyzmq=15.4.0=py35_0
qt=5.6.2=2
qtconsole=4.3.1=py35_0
requests=2.11.1=py35_0
scikit-learn=0.17.1=np111py35_2
scipy=0.18.0=np111py35_0
seaborn=0.7.1=py35_0
setuptools=26.1.1=py35_0
simplegeneric=0.8.1=py35_1
sip=4.18=py35_0
six=1.10.0=py35_0
sqlalchemy=1.1.6=py35_0
statsmodels=0.6.1=np111py35_1
terminado=0.6=py35_0
toolz=0.8.0=py35_0
tornado=4.4.1=py35_0
traitlets=4.3.1=py35_0
wcwidth=0.1.7=py35_0
wheel=0.29.0=py35_0
widgetsnbextension=3.0.2=py35_0
xarray=0.8.2=py35_0
xz=5.2.2=0
yaml=0.1.6=0
zlib=1.2.11=0

**Comment by Freedomtowin** [comment]
The logic board was fried and the Apple repair shop replaced it. I'm not sure if ipyparallel overrides any safety mechanism in the computer or if I received a faulty Mac book. 

This ticket can be closed.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

Feel free to open a new Issue if you are still having this trouble. In particular, share what is actually slow with examples, timings, etc. I'm going to hope this was an intermittent issue and fixed in the meantime, but feel free to reopen if you can reproduce it with current versions of packages.
