### ISSUE TITLE
ipython_genutils has been dropped - do not use it

### ISSUE THREAD

**Issue by opoplawski** [ipython/ipyparallel#358]
https://pypi.org/project/ipython_genutils/ states:

Pretend this doesn’t exist. Nobody should use it.

**Comment by minrk** [comment]
Yes, I created that package when the Jupyter Big Split happened. It really means nothing *outside* IPython and Jupyter should use it, though we should be weaning our packages off of it eventually. There's no harm in its continued presence in IPython packages, though.
