### ISSUE TITLE
error in launch of jupyter notebook

### ISSUE THREAD

**Issue by rajat997** [ipython/ipyparallel#359]
![Capture0](https://user-images.githubusercontent.com/48414681/54089074-f535c380-438a-11e9-87c4-c8f6f47ef1e1.PNG)
everytime I launch jupyter notbook I encounter this even if internet connection is fine

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time! I think this is a jupyter notebook issue, and not related to IPython parallel.
