### ISSUE TITLE
ipcluster has no client ids

### ISSUE THREAD

**Issue by natsrm** [ipython/ipyparallel#362]
Hi!
I wanted to use ipcluster with Windows 10 but when I call it in the cmd line (Anaconda prompt), it shows as if my engines have started successfully but when I want to get the client ids to make sure everything is okay, I have no ids. I have tried definig the path to the JSON file but it still does not work... However when I try using ipcontroller and ipengine, it works fine. Is there something I might be doing wrong? I have tried to see the log file but it's not even being created... The code I used is as follow (with $ in the beggining means it is in cmd line, with the numbers means it is in the spyder console):

`$ ipcluster start -n 3`
`In [1]: import ipyparallel as ipp`
`In [2]: c = ipp.Client()`
(or `In [2]: c = ipp.Client('C:/Users/.ipython/profile_default/security/ipcontroller_client.json')`)
`In [3]: c.ids`
`Out [3]: []`

Code with ipcontroler and ipengine:

`$ ipcontroller`
(new window) `$ ipengine`
(new window) `$ ipengine`
(new window) `$ ipengine`
`In [1]: import ipyparallel as ipp`
`In [2]: c = ipp.Client()`
`In [3]: c.ids`
`Out [3]: [0, 1, 2]`

Thanks in advance!

**Comment by minrk** [comment]
Can you run `ipcluster start --debug` and/or check the ipcontroller and ipengine logs? My guess is that the engines aren't registering.

**Comment by natsrm** [comment]
I run `ipcluster start --debug` and this was the output
![image](https://user-images.githubusercontent.com/43876521/57527428-88f22480-7327-11e9-8d41-2899192fb8f1.png)

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

Feel free to open a new Issue if you are still having this trouble.

With recent versions of ipyparallel `--debug` includes the controller and engine outputs, which means that depending on configuration, you might not be using the current version. Try making sure everything is up-to-date and trying again.
