### ISSUE TITLE
Test failure on Fedora 31 (rawhide)

### ISSUE THREAD

**Issue by ellert** [ipython/ipyparallel#375]
The test suite fails on Fedora 31:
~~~~
=================================== FAILURES ===================================
_____________________________ TestView.test_abort ______________________________

self = <ipyparallel.tests.test_view.TestView testMethod=test_abort>

    def test_abort(self):
        view = self.client[-1]
        ar = view.execute('import time; time.sleep(1)', block=False)
        ar2 = view.apply_async(lambda: 2)
        view.abort(ar2)
        ar3 = view.apply_async(lambda: 3)
        view.abort(ar3.msg_ids)
>       self.assertRaises(error.TaskAborted, ar2.get)
E       AssertionError: TaskAborted not raised by get

ipyparallel/tests/test_view.py:383: AssertionError
~~~~
Installed deps:

python3-3.7.4-3.fc31.x86_64
python3-dateutil-2.8.0-1.fc30.noarch
python3-decorator-4.4.0-1.fc31.noarch
python3-devel-3.7.4-3.fc31.x86_64
python3-ipykernel-5.1.1-1.fc31.noarch
python3-ipython-7.6.1-1.fc31.noarch
python3-ipython_genutils-0.1.0-17.fc31.noarch
python3-jupyter-client-5.2.3-7.fc30.noarch
python3-jupyter-core-4.4.0-7.fc30.noarch
python3-nose-1.3.7-23.fc31.noarch
python3-numpy-1.16.4-2.fc31.x86_64
python3-pytest-4.6.4-2.fc31.noarch
python3-tornado-6.0.2-1.fc31.x86_64
python3-traitlets-4.3.2-9.fc30.noarch
python3-zmq-18.0.2-1.fc31.x86_64
python3-zmq-tests-18.0.2-1.fc31.x86_64

It works on Fedora 30 with the following deps:

python3-3.7.3-3.fc30.x86_64
python3-dateutil-2.8.0-1.fc30.noarch
python3-decorator-4.3.0-2.fc30.noarch
python3-devel-3.7.3-3.fc30.x86_64
python3-ipykernel-5.1.1-1.fc30.noarch
python3-ipython-7.2.0-2.fc30.noarch
python3-ipython_genutils-0.1.0-16.fc30.noarch
python3-jupyter-client-5.2.3-7.fc30.noarch
python3-jupyter-core-4.4.0-7.fc30.noarch
python3-nose-1.3.7-22.fc30.noarch
python3-numpy-1.16.4-2.fc30.x86_64
python3-pytest-3.9.3-2.fc30.noarch
python3-tornado-5.0.2-5.fc30.x86_64
python3-traitlets-4.3.2-9.fc30.noarch
python3-zmq-17.0.0-4.fc30.x86_64
python3-zmq-tests-17.0.0-4.fc30.x86_64

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

Feel free to open a new Issue if you are still having this trouble. I suspect this is fixed by recent versions.
