### ISSUE TITLE
Installation path of data_files

### ISSUE THREAD

**Issue by marbre** [ipython/ipyparallel#377]
Currently, the data_files get installed to ``/usr/etc`` by Gentoo's ebuild, as reported [here](https://bugs.gentoo.org/688258). In order to fix the ebuild, I would like to ask if it is intended to install the files to ``/etc`` or if another location is expected.

**Comment by jnahmias** [comment]
I'm in the process of preparing packages for Debian. For that purpose, I am overriding the install directory for those `.json` files from `/usr/etc/` => `/etc`. Not sure if it's a typo/bug, but it's definitely incorrect on Debian.

**Comment by minrk** [comment]
ipyparallel doesn't (in fact cannot) specify the prefix for data_files to go in, only that it should go in the appropriate `$something/etc`. Where they go is up to the distutils installation scheme. If the package-wrapper puts data_files in the wrong place, debian's or gentoo's distutils scheme is where there is something to be fixed.
