### ISSUE TITLE
AsyncResult._wait_for_output is too heavy on the CPU

### ISSUE THREAD

**Issue by Zaharid** [ipython/ipyparallel#38]
When I launch several independent jobs and `wait()` for them in a PBS cluster, each of them consumes around 60% of the CPU for just waiting. This makes it really inconvenient to launch several jobs from a shared main node that many people are using. I notice that the sleep timeout is just 0.01 seconds which seems very short to me (especially if I expect the job to take hours).

The fanciest would be a sleeping time that increases over time itself (up to some max value).

**Comment by minrk** [comment]
I don't think this used to use so much CPU, I wonder what happened. The exponential falloff is implemented in #39, reducing CPU usage below 0.5% for me.
