### ISSUE TITLE
plotly

### ISSUE THREAD

**Issue by pradeep2022** [ipython/ipyparallel#381]
plotly is not importing in jupyter notebook

**Comment by eXaz** [comment]
@pradeep2022 Unfortunately this is not very helpful. As this is your first issue maybe read up on best practises for creating issues on github e.g. [https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md](https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md)
