### ISSUE TITLE
Error tcp connect

### ISSUE THREAD

**Issue by sonfire86** [ipython/ipyparallel#390]
` rc = ipp.Client('tcp://192.168.1.16:10101')`

`single urls cannot be specified, url-files must be used.`

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

As the error message suggests, a URL is not a valid input to constructing a Client. You must pass either a profile name or path to connection file.
