### ISSUE TITLE
Cluster stops unexpectedly

### ISSUE THREAD

**Issue by guptakartik** [ipython/ipyparallel#391]
Hi @minrk 

While using ipyparallel with engines on localhost (started using the command ipcluster start -n 10), I am facing this issue where if my jobs take some amount of time to finish (> 2 hours) the cluster stops unexpectedly on it's own. My program schedules jobs to the controller and usually the first few batches finish successfully. The python program in jupyter notebook sits idle expecting a reply from the engines but failing to do so since they stopped. On stopping my engines using ipcluster stop I get the following message:  CRITICAL | Cluster [pid=990] is not running.

I am not sure what is causing the cluster to stop running by itself. I have faced this issue on multiple different machines (Windows and Ubuntu) and it tends to arise with jobs that take a while to get over.

Any help would be appreciated! Thanks!

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

Feel free to open a new Issue if you are still having this trouble.

I don't know what could be causing the controller to stop after a while, but in some contexts a resource exhaustion crash could be related. Try running `ipcontroller` outside `ipcluster` and capturing the output to see if you get interesting info when the process finally exits.
