### ISSUE TITLE
Client() constructor bug in check for 'px' in the registered magics

### ISSUE THREAD

**Issue by philtrade** [ipython/ipyparallel#392]
In ipyparallel/client/client.py, near the end of the constructor `Client.__init__(...)`:

`            if 'px' not in ip.magics_manager.magics:`

should go one level deeper, because `ip.magics_manager.magics.keys()` returns: `dict_keys(['line', 'cell'])`.   Perhaps use lsmagic() instead of peeking at `.magics` directly:

`            if 'px' not in ip.magics_manager.lsmagic()['cell']:`

I'd be happy to submit a PR for this.  Thanks.

**Comment by minrk** [comment]
Fixed by #441
