### ISSUE TITLE
Multithreading problem with numpy/MKL and ipyparallel [Solved]

### ISSUE THREAD

**Issue by freedomtowin** [ipython/ipyparallel#393]
It seems that Anaconda's distribution of numpy is using MKL which uses multiple threads.

This has been a thorn in my side for over a year as it makes parallel processing damn near impossible.

This can be used to set the number of threads numpy uses for each core.

`dview.execute('numpy.mkl.set_num_threads(2)')`

**Comment by minrk** [comment]
Closing as the issue contains is own resolution
