### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by cometta** [ipython/ipyparallel#399]
May I know what is the steps to do debug using ptvsd? how to debug function that run inside an engine?

**Comment by minrk** [comment]
You can use [debugpy](https://github.com/microsoft/debugpy/) in an IPython engine and attach e.g. [vs code](https://code.visualstudio.com/Docs/editor/debugging#_launch-versus-attach-configurations) to an engine's process:

```python
import ipyparallel as ipp

rc = ipp.Client()


def trigger_debug():
    a = 5
    import debugpy

    debugpy.listen(5678)
    debugpy.wait_for_client()

    def foo():
        local_a = 10
        1 / 0

    foo()


rc[0].apply_sync(trigger_debug)
```

Which ips and ports you choose will depend on where your engine is relative to the debugger client.
