### ISSUE TITLE
Why is the method to obtain a ipyparallel.DirectView implemented like a slice operator?

### ISSUE THREAD

**Issue by alex4200** [ipython/ipyparallel#402]
In the code you usually do something like

```
import ipyparallel as ipp
c = ipp.Client()
c[:].apply_sync(lambda : "Hello, World")
```

where you have the method `[:]` to create a ` ipyparallel.DirectView` object. Why is the 'slice' operator used for that? I find this EXTREMLY confusing and VERY non-intuitive!

See also [HERE](https://www.python.org/dev/peps/pep-0020/)

**Comment by minrk** [comment]
A client is treated as a 'container of engines', so using the standard Python syntax for 'all items' requests a view , which is a slice with None. You can also slice the target ids, e.g. `rc[::2]` for even/odd engines if you want to easily partition your engines.

You can also use explicit method calls if you prefer:

```python
view = client.direct_view(targets='all')
```
