### ISSUE TITLE
[Feature Request] lazy map like `multiprocessing.Pool.imap`

### ISSUE THREAD

**Issue by ZisIsNotZis** [ipython/ipyparallel#411]
I'm working on processing video frames. Since each frame is individual, I use ipyparllel to distrubute the computation onto multiple nodes so that the process can get faster.

But since one frame is 1920x1080x3 bytes, and a video will have thousands of frame inside, ipyparallel will run out of memory trying to extract all frames from the video.

In python3 `multiprocessing.Pool.imap`, the iterator will iterate only if there's a free node (when chunk size=1). It waits otherwise. Can such functionality be implemented in ipyparallel? I believe this should be very useful in terms of (possibly) very long iterator (and stream processing).

Thanks!

**Comment by minrk** [comment]
Yes, this should be possible. You can do it today with a lazy_map function:

```python
from collections import deque


def lazy_map(view, f, *seqs, max_outstanding=None):
    if max_outstanding is None:
        # default: limit to one task per engine
        max_outstanding = len(view.client)

    outstanding = deque()
    # zip is a lazy iterator
    for args in zip(*seqs):
        # submit one work item
        ar = view.apply_async(f, *args)
        outstanding.append(ar)
        # count 'pending' tasks
        # yield first result if it's ready
        # *or* the number of outstanding tasks has reached our limit
        if outstanding[0].ready() or sum(not ar.ready() for ar in outstanding) >= max_outstanding:
            first_ar = outstanding.popleft()
            yield first_ar.get()
        # we've filled the buffer, wait for a result before continuing
        if len(outstanding) == max_outstanding:
            first_ar = outstanding.popleft()
            yield first_ar.get()
    
    # yield any remaining results
    for ar in outstanding:
        yield ar.get()

for i, _ in enumerate(lazy_map(view, time.sleep, range(10)):
    print(i)
```
