### ISSUE TITLE
using ipyparallel on slurm cluster in ML application, and only getting Nan scores in fitting.

### ISSUE THREAD

**Issue by johnmichaloski** [ipython/ipyparallel#412]
Background: NIST has a cluster (13) of IBM PowerPC nodes/cpus/cores/etc that are programmed using SLURM and share a file system. Since ipyparallel was ported by IBM to powerpc I used it in a python application to speed up sklearn GridSearchCV for a Keras (tf2) maching learning hyperparameter evaluation using ipyparallel as the joblib  parallel_backend .

I successfully have used the ipyparallel documented example to embed a srun inside of sbatch according to the documentation and it appears to be launching jobs on one or more nodes on different cores, however, all the fit/trains have Nan scores. 

I’m guessing the input may be the problem. Data is a 1800 line 18 column csv file (12 input, 6 output per line) that is read each time by a job using pandas to read csv file  and then used by Keras ML multi input/output regressor after converted into numpy. 

I have run SLURM using joblib with multiprocessing, threading, and loky on one node/multiple jobs/ multiple cores, and get real keras ML training results. 

Thoughts or pointers appreciated.

TIA,
John
==============================================================================

```bash
SLURM script:
#!/bin/bash -l

#SBATCH --partition=gpu            # debug, general or gpu paritionss	
#SBATCH --ntasks=40                   # Run n tasks	
#SBATCH --nodes=1                    # Run all processes on N nodes	
#SBATCH --time=5-00:00:00               # 
#SBATCH --cpus-per-task=1            # Number of CPU cores per task max = 3 nodes x 2 cpu/node x 20 core/cpu
#SBATCH --threads-per-core=4
#SBATCH --job-name=ipy_1node
#SBATCH --mail-user=john.michaloski@nist.gov
#SBATCH --output=pygs_test_%j.log
#SBATCH --gres=gpu:4 # This is here to make enki happy about using gpu

conda activate py37
profile=job_${SLURM_JOB_ID}
ipython profile create ${profile}

ipcontroller --ip="*" --profile=${profile} &
sleep 10

srun ipengine --profile=${profile} --location=$(hostname)  &
sleep 25

python /home/michalos/Tune/IKTrainNNScikitOptGrid.py -p ${profile}
```

Python code:

```python
from sklearn.externals.joblib import Parallel, parallel_backend
from sklearn.externals.joblib import register_parallel_backend
from sklearn.externals.joblib import delayed
from sklearn.externals.joblib import cpu_count
from ipyparallel import Client
from ipyparallel.joblib import IPythonParallelBackend

. . .
if __name__ == '__main__':
    regressor = tf.keras.wrappers.scikit_learn.KerasRegressor \
        (build_fn=MLmodel.baseline_model,
         batch_size=batch_size,
         epochs=epochs,
         verbose=2
         )

    rscv = GridSearchCV(regressor,
                        param_grid=params,
                        refit=True,
                        cv=2,
                        verbose=2,
                        n_jobs=10 )

   # inside if statement ...

        c = Client(profile=profile)
        c[:].map(os.chdir, [FILE_DIR]*len(c))
        logging.info("c.ids :{0}".format(str(c.ids)))
        print("Client ids", c.ids)
        bview = c.load_balanced_view()

        # this is taken from the ipyparallel source code
        register_parallel_backend('ipyparallel', lambda : IPythonParallelBackend(view=bview))

        with parallel_backend('ipyparallel'):
            rscv_results = rscv.fit(x_train, y_train )
```

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

Can you provide a *complete* example where this happens? It's hard to debug without code I can run. I wouldn't know where to begin isolating the source of NaNs that are unique to IPP and not joblib. Does it happen when you run with a local ipyparallel cluster as well, or only on SLURM? Feel free to close if you are not facing this anymore.

**Comment by johnmichaloski** [comment]
Gave up. Close it.
