### ISSUE TITLE
Failing RTD doc builds

### ISSUE THREAD

**Issue by willingc** [ipython/ipyparallel#42]
The absence of a ``requirements.txt`` file is causing the builds to fail.

Recommend removing the requirements.txt file from the Advanced Setting tab in RTD and rebuild latest docs.
<img width="858" alt="screen shot 2015-09-26 at 6 52 48 pm" src="https://cloud.githubusercontent.com/assets/2680980/10120742/c88f2f2a-6480-11e5-95e6-36ad920bee78.png">

**Comment by minrk** [comment]
Thanks for the notice. I made the recommended change, and it's building now.

**Comment by willingc** [comment]
@minrk :smile_cat:
FYI - I have a simple markdown file that I made to quickly scan doc build status https://github.com/willingc/planetgazer/blob/master/STATUS_slim.md
