### ISSUE TITLE
ipcluster and ipcontroller-client.json not found

### ISSUE THREAD

**Issue by davidsplint** [ipython/ipyparallel#423]
I'm trying to follow [these](https://ipyparallel.readthedocs.io/en/latest/intro.html) instructions on using `ipyparallel` in order to speed up some Python scripts in Jupyter Notebook. When doing

    import ipyparallel as ipp
    IPPC = ipp.Client()

I get the following error:

    Using matplotlib backend: TkAgg
    
    Waiting for connection file: ~/.ipython/profile_default/security/ipcontroller-client.json
    
    ---------------------------------------------------------------------------
    OSError                                   Traceback (most recent call last)
    <ipython-input-11-bf8e572b63bc> in <module>()
         18 display(HTML("<style>.container {width:100% !important;}</style>"))
         19 
    ---> 20 IPPC = ipp.Client()
         21 
         22 
    
    /home/guest/.local/lib/python3.7/site-packages/ipyparallel/client/client.py in __init__(self, url_file, profile, profile_dir, ipython_dir, context, debug, sshserver, sshkey, password, paramiko, timeout, cluster_id, **extra_args)
        415                         no_file_msg,
        416                     ])
    --> 417                     raise IOError(msg)
        418         if url_file is None:
        419             raise IOError(no_file_msg)
    
    OSError: Connection file '~/.ipython/profile_default/security/ipcontroller-client.json' not found.
    You have attempted to connect to an IPython Cluster but no Controller could be found.
    Please double-check your configuration and ensure that a cluster is running.

The file `~/.ipython/profile_default/security/ipcontroller-client.json` does not exist (folder is *empty*!!) and doing `sudo find / -name ipcontroller-client` doesn't return any results.

Furthermore, when trying to start `ipcluster` in the terminal, I get

    user@laptop:~$ ipcluster start -n 2
    ipcluster: command not found

and the "Clusters" tab in Jupyter Notebook is empty: [***Screenshot***][1]

However, `ipyparallel` is definitely installed:

    user@laptop:~$ pip3 install ipyparallel
    Requirement already satisfied: ipyparallel in ./.local/lib/python3.7/site-packages (6.3.0)
    Requirement already satisfied: jupyter-client in /usr/lib/python3/dist-packages (from ipyparallel) (5.2.3)
    Requirement already satisfied: traitlets>=4.3 in /usr/lib/python3/dist-packages (from ipyparallel) (4.3.2)
    Requirement already satisfied: tornado>=4 in /usr/lib/python3/dist-packages (from ipyparallel) (5.1.1)
    Requirement already satisfied: pyzmq>=13 in /usr/lib/python3/dist-packages (from ipyparallel) (17.1.2)
    Requirement already satisfied: ipykernel>=4.4 in /usr/lib/python3/dist-packages (from ipyparallel) (4.9.0)
    Requirement already satisfied: ipython-genutils in /usr/lib/python3/dist-packages (from ipyparallel) (0.2.0)
    Requirement already satisfied: decorator in /usr/lib/python3/dist-packages (from ipyparallel) (4.3.0)
    Requirement already satisfied: ipython>=4 in /usr/lib/python3/dist-packages (from ipyparallel) (5.8.0)
    Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3/dist-packages (from ipyparallel) (2.7.3)
    Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (from ipython>=4->ipyparallel) (4.6.0)

and there are three Python scripts `ipcluster`, `ipcontroller`, and `ipengine` in `/home/user/.local/bin`.

What is the problem?

  [1]: https://i.stack.imgur.com/RvEr4.png

**Comment by minrk** [comment]
> What is the problem?

The first problem, as the error message suggests:

> You have attempted to connect to an IPython Cluster but no Controller could be found.
> Please double-check your configuration and ensure that a cluster is running.

is that you have attempted to connect to a cluster (`ipp.Client()`) without starting one first (`ipcluster`). You must start a cluster before connecting to it.

The second problem is what's preventing you from starting a cluster:

> `ipcluster: command not found`
> and there are three Python scripts `ipcluster`, `ipcontroller`, and `ipengine` in `/home/user/.local/bin`.

which is that `$HOME/.local/bin` is not on $PATH. This is where pip installs scripts when you do `pip install --user`. If you want your shell to be able to find programs installed by pip, add this to PATH, which you can do interactively or in your `~/.bashrc`:

```bash
export PATH=$HOME/.local/bin:$PATH
```

then `ipcluster` will work.

**Comment by davidsplint** [comment]
Hi,

thanks a lot, this seemed to have helped:

    user@laptop:~$ ipcluster start -n 2
    2020-08-20 02:33:21.744 [IPClusterStart] Starting ipcluster with [daemon=False]
    2020-08-20 02:33:21.746 [IPClusterStart] Creating pid file: /home/guest/.ipython/profile_default/pid/ipcluster.pid
    2020-08-20 02:33:21.747 [IPClusterStart] Starting Controller with LocalControllerLauncher
    2020-08-20 02:33:22.758 [IPClusterStart] Starting 2 Engines with LocalEngineSetLauncher
    2020-08-20 02:33:52.891 [IPClusterStart] Engines appear to have started successfully

In Jupyter Notebook, I now get:

    import ipyparallel as ipp
    ippc = ipp.Client()
    ippc.ids
    
    Output[10]: [0, 1]

However, there is still nothing showing up in the "Clusters" tab in Jupyter. How can I check if this is working?

**Comment by minrk** [comment]
yes, everything is working. To enable the notebook extension, you can run:

    ipcluster nbextension enable

and restart the notebook server

**Comment by davidsplint** [comment]
What happen if I enable the notebook extension (never worked with extensions before...)?

Actually, I'm getting an error for `ipcluster nbextension enable`:

```
user@laptop:~$ ipcluster nbextension enable
Enabling IPython clusters tab
Traceback (most recent call last):
  File "/home/user/.local/bin/ipcluster", line 10, in <module>
    sys.exit(launch_new_instance())
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/user/.local/lib/python3.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 674, in start
    return self.subapp.start()
  File "/home/user/.local/lib/python3.7/site-packages/ipyparallel/apps/ipclusterapp.py", line 637, in start
    install_extensions(enable=True, user=self.user)
  File "/home/user/.local/lib/python3.7/site-packages/ipyparallel/nbextension/install.py", line 24, in install_extensions
    toggle_serverextension_python('ipyparallel.nbextension', user=user)
  File "/usr/lib/python3/dist-packages/notebook/serverextensions.py", line 74, in toggle_serverextension_python
    cm.update("jupyter_notebook_config", cfg)
  File "/usr/lib/python3/dist-packages/notebook/config_manager.py", line 136, in update
    self.set(section_name, data)
  File "/usr/lib/python3/dist-packages/notebook/config_manager.py", line 110, in set
    self.ensure_config_dir_exists()
  File "/usr/lib/python3/dist-packages/notebook/config_manager.py", line 67, in ensure_config_dir_exists
    os.makedirs(self.config_dir, 0o755)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/etc/jupyter'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True
```

There seems to be a permission error, but doing `sudo ipcluster nbextension enable` throws an error as well:

```
user@laptop:~$ sudo ipcluster nbextension enable
[sudo] password for user:              
sudo: ipcluster: command not found
```

**Comment by minrk** [comment]
try:

    ipcluster nbextension enable --user

**Comment by minrk** [comment]
> Do you see what's the problem here?

Yes, two problems:

1. in this example, trying to parallelize a 1ms task is unlikely to improve, because for just one call there is an overhead on the order of a few milliseconds to schedule the task and retrieve the results. Pipelining several calls can mitigate this, but in general, tasks need to be at least several milliseconds for there to be any benefit.

2. this code asks each engine to do the exact same work you are doing in serial, which means you are doing N times the amount of work, not parallelizing the same workload.

The code `par.apply(fibonacci, 1000)` is saying:

> Every engine call `fibonacci(1000)` and collect the results.

Parallelizing Fibonacci is not a particularly good fit for IPython parallel because of the strong dependency of each element on previous computations. A task-graph-style tool, such as [dask](https://distributed.dask.org), is probably a better fit, if you look up parallel fibonacci algorithms. The dask docs include [fibonacci as an example](https://distributed.dask.org/en/latest/task-launch.html). In particular, submitting tasks from engines is not well supported in IPython Parallel (you can create clients and submit and wait for tasks, but this will deadlock promptly due to the lack of `secede()` and `rejoin()` features in dask), which I think is required for a tractable parallel implementation of a recursive algorithm like Fibonacci.

If you do want to test simple parallelism in IPython Parallel, a monte carlo algorithm such as [this approximation of π](https://gist.github.com/1d368532f0761377fda7f1596b35e206) is a better fit, and shows that you need tasks of at least several milliseconds to benefit from the scheduling overhead.

**Comment by davidsplint** [comment]
Thanks again for your detailed answer! Do I understand it correctly that it takes a certain "type/class" of problem so that it can be parallelized? Of course, my goal is not to get some Fibonacci numbers, but some basic image processing (short pseudocode):

```
def function_1    # Some function...
def function_2    # Some other function...

for imageStack in imageStackList:    # Big images with multiple frames
    image = averageOverFrames(imageStack)
    fit = curve_fit(function_1, image)
    convolution = convolve(fit, function_2)
    plot(imageAverage, fit, residuals, function_1, function_2, convolution)

It's just using NumPy and SciPy to take some TIFF image stacks, do a fit, then a convolution, then plot everything.

Is IPython Parallel applicable to this problem?
```

**Comment by davidsplint** [comment]
PS.: Processing 15 images currently takes about 3-4 min

**Comment by minrk** [comment]
> Do I understand it correctly that it takes a certain "type/class" of problem so that it can be parallelized?

IPython Parallel does not parallelize your code. It allows *you* to parallelize your code through methods such as `map` or asynchronous calls to `apply`. If you can express your code in this way, where concurrency is explicit through submitting execution at one point and then retrieving results at a later point, then it can be expressed in IPython Parallel.

> Is IPython Parallel applicable to this problem?

The example you have here corresponds to a `map` (calling one function on a sequence of inputs), which can be parallelized with IPP, or many other tools:

```python
def process_image(image_stack):
    image = averageOverFrames(imageStack)
    fit = curve_fit(function_1, image)
    convolution = convolve(fit, function_2)
    return image, fit, convolution

for (image, fit, convolution) in view.map(process_image, image_stack_list):
    plot(...)
```

Depending on your circumstances, the `plot` call might go inside process_image so it's done in parallel (e.g. saving figures to files), or locally so you can control the plots interactively and work with the underlying data.
