### ISSUE TITLE
jupyterhub not seeing running ipclusters

### ISSUE THREAD

**Issue by mkgilbert** [ipython/ipyparallel#44]
I have Jupyterhub 0.2.0 and ipyparallel 4.0.2 installed and working and can successfully start an ipcluster using the "ipython clusters" tab of the web interface. I've confirmed that the engines are running by creating a basic notebook that prints out the id's of the running engines:

from ipyparallel import Client
c = Client(profile='default')
c.ids

The notebook shows the ids correctly. The problem is, when I stop the server from the control panel, start it back up again, and I click over to the "ipython clusters" tab, it says there are none running. However, the engines are still running in my process tree when I do `ps aux|grep ipyparallel`. When I re-run the notebook it still sees the engines and prints out the ids.

Is this a known issue? I plan on using this in a cluster-computing environment using a scheduling system, so users will need to see if they have ipclusters running. As of now, users will be checking the tab, maybe seeing erroneous information and starting up potentially a whole bunch of different clusters. This would create a bit of a management nightmare. Any thoughts?

**Comment by minrk** [comment]
The clusters tab is only aware of clusters that it has started. It doesn't have any awareness or control over clusters that it did not start, so you should be aware of that. I'm not aware of the clusters tab losing track of its own clusters, though. Maybe it's getting confused during the restart and thinking it should be removing the cluster that it just started. Can you show the logs of the notebook server when this happens (JupyterHub shouldn't be relevant, just the notebook server)?

I do plan to completely change how ipcluster works (make it a service instead of a script), at which point clusters started by any means should appear in the tab.

**Comment by mkgilbert** [comment]
Thank you so much for the reply! I apologize for taking so long getting
back to you. I wasn't aware that Notebook had a separate log file,
actually. I've been looking through the docs trying to find where it would
be stored, but I'm not having any luck. I also tried adding
"c.NotebookApp.log_file = /path/to/file", "c.NotebookApp.extra_log_file =
/path/to/file", and the same for "JupyterApp" but the log file never gets
generated. How do I go about specifying the log file for Notebook?

Thanks!

Mike

**Comment by mkgilbert** [comment]
I can't seem to find where the notebook sends its logs to...I don't see a spot for that in config. Is there a way to specify the notebook log file?

**Comment by polarizeme** [comment]
Having this same issue, just to throw another hat on the pile.

If any of our JupyterHub users start a number of engines through the clusters tab and then shut their servers down without stopping the engines first, the next time they start their hub server it won't see the running engines anymore in the clusters tab, but using

from ipyparallel import Client
c = Client(profile='default')
c.ids

in a notebook will still output the started engines from the previous session and I can still see them running w/  `ps aux`.

**Comment by minrk** [comment]
this is fixed in the new clusters extension in 7.0, which is aware of clusters started via any mechanism, be it the extension, `ipcluster start`, or the new `ipp.Cluster` API.
