### ISSUE TITLE
Example with prose using with `concurrent.futures` API

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipyparallel#459]
In PR ( https://github.com/ipython/ipyparallel/pull/80 ) ipyparallel added support for the `concurrent.futures` API. This is a handy feature as it allows ipyparallel to be more easily used by other libraries that accept/work with an `Executor` as defined in that API. Outside of API documentation for creating a [`concurrent.futures.Executor`]( https://ipyparallel.readthedocs.io/en/latest/api/ipyparallel.html#ipyparallel.Client.executor ), there doesn't appear to be documentation explaining how one might use this. It might be worth including a little bit of prose along with a short example to help users get started, who otherwise might not know how to.

**Comment by jakirkham** [comment]
One possible example might be something like this:

Start up a local ipyparallel `Client`:

```bash
$ ipcluster start -n 4
```

In IPython or a Jupyter Notebook, run some code like the following: 

```python
import ipyparallel as ipp


c = ipp.Client()
e = c.executor()

list(e.map(lambda i: 2 * i, range(5)))
```

Here `e` is an `Executor` subclass instance.

**Comment by minrk** [comment]
Great idea! I have time to work on IPython Parallel right now, and am hoping to do a good pass on the docs. I'll definitely include this.

**Comment by jakirkham** [comment]
Awesome thanks Min! 😄

Happy to read over a draft if you need another pair of eyes 🙂

**Comment by minrk** [comment]
Working on the docs now in #555. Example using Executors is [here](https://ipyparallel--555.org.readthedocs.build/en/555/examples/Futures.html#Executors) if you want to have a look.
