### ISSUE TITLE
[Feature] Cluster Manager Python API

### ISSUE THREAD

**Issue by sahil1105** [ipython/ipyparallel#460]
It would be good to have a ClusterManager object which can start the engines using MPI, keep tabs on the `mpiexec` process, report crash to controller (with exit code, etc.), etc. This should also remove the need for heartbeats since `mpiexec` already monitors health of the engines. In case of a crash, we can quickly inform the controller (which can then inform the client).
We can also provide pythonic APIs to start and restart engines. Users could provide additional parameters for `mpiexec` when starting the engines, like rank-placement (round-robin, etc.) and so on.
Interrupts can be handled through this object as well (send signal to `mpiexec`, etc.). 
Deleting the object should stop the engines and clean up the memory. Running the code again would start a new set of engines.

---

EDIT: linked issues: #22, #44, #216, #243, #241

**Comment by minrk** [comment]
Writing down some notes with what I have in mind here:

- Cluster object represents a single cluster (one controller + 0-many EngineSets), re-using our existing Launcher code
  - start/stop controller
  - start/stop/signal/restart engines (*may* be only at EngineSet level for limited implementations such as mpiexec/qsig)
  - notify controller on engine exit
  - context manager API for requesting resources and cleanup on exit
- ClusterManager manages several Cluster objects by id (much like notebook server's MultiKernelManager), mostly exposing the same methods with a `cluster_id` argument, plus list_clusters/new_cluster
- Later: wrap ClusterManager in a REST API for e.g. a JupyterLab extension and managing remote clusters
