### ISSUE TITLE
Abort not work

### ISSUE THREAD

**Issue by GF-Huang** [ipython/ipyparallel#506]
After call `Client.Abort()`, still full CPU usage.

![image](https://user-images.githubusercontent.com/4510984/123694660-2ef8a400-d88c-11eb-9973-d353cc065512.png)

**Comment by minrk** [comment]
Abort does not cancel running tasks, it only prevents queued tasks from starting. To cancel tasks, you'll need to send SIGINT to engines

**Comment by GF-Huang** [comment]
I had try `ipcluster stop`, but CPU still 100%.

**Comment by minrk** [comment]
Please provide more information:

- OS
- Python, ipyparallel version
- how you started the cluster
- what Launcher is used

**Comment by GF-Huang** [comment]
If I call `client.abort()` then `ipcluster stop` it still 100%, but if I only `ipcluster stop`, it stopped.

**Comment by GF-Huang** [comment]
@minrk Any progress? Or any workaround?

**Comment by minrk** [comment]
Can you try again with master? I think `ipcluster stop` should work in that case. You can also try using the [`Cluster.signal_engines` API](https://ipyparallel.readthedocs.io/en/latest/examples/Cluster%20API.html) if you are using 7.0.

**Comment by minrk** [comment]
If you're using local engines, `os.kill` also works to interrupt/shutdown engines:

```python
import os
pid_map = rc[:].apply_async(os.getpid).get_dict()

def signal_engine(engine_id, sig):
    pid = pid_map[engine_id]
    os.kill(pid, sig)
```

**Comment by GF-Huang** [comment]
If I use the Cluster API, the `%px` magic stucks.

![image](https://user-images.githubusercontent.com/4510984/124290508-15a27100-db86-11eb-9070-2e1512212916.png)

![image](https://user-images.githubusercontent.com/4510984/124290437-01f70a80-db86-11eb-8e7a-b943dbfef148.png)

**Comment by GF-Huang** [comment]
Call `client.activate()` solved.
