### ISSUE TITLE
How to real time print when using parallel map?

### ISSUE THREAD

**Issue by GF-Huang** [ipython/ipyparallel#507]
My parallel task maybe duration a few hours or days, how can I know the progress?

Don't tell me the `wait_interactive`, it's not a good way for me.

![image](https://user-images.githubusercontent.com/4510984/123702669-fe1d6c80-d895-11eb-9548-50017f911071.png)

**Comment by minrk** [comment]
Useful attributes on AsyncResult:

- `AsyncResult.wait([timeout])` waits up to a timeout for a result to be done
- `AsyncResult.progress` is the number of completed tasks
- `len(AsyncResult)` is the total number of tasks
- `AsyncResult.elapsed` is the number of seconds the task has been running

AsyncResult.wait_interactive is [one implementation](https://github.com/ipython/ipyparallel/blob/1bd435d8e30146ad6eefcc55c9e33009321d1cdd/ipyparallel/client/asyncresult.py#L492-L503) of waiting and displaying progress, based on these attributes, which you can use for reference, but do whatever makes sense for you.

See [the docs](https://ipyparallel.readthedocs.io/en/6.2.3/asyncresult.html#timing) for more info about these attributes.

**Comment by GF-Huang** [comment]
I'm using this to solve the issue:

```py
import sys
import time
from IPython.display import clear_output

def wait_watching_stdout(ar, refresh_interval=1):
    while not ar.ready():
        stdouts = ar.stdout
        if not any(stdouts):
            continue
        # clear_output doesn't work in plain terminal / script environments
        clear_output()
        print('-' * 30)
        print("%.3fs elapsed" % ar.elapsed)
        print()
        for eid, stdout in zip(range(len(ar.stdout)), ar.stdout):
            if stdout:
                print("[ stdout %2i ]\n%s" % (eid, stdout.rsplit('\n', 2)[-2]))
        sys.stdout.flush()
        time.sleep(refresh_interval)
```
