### ISSUE TITLE
Progress bars can close before completing

### ISSUE THREAD

**Issue by minrk** [ipython/ipyparallel#526]
Interactive waits use tqdm progress bars. These are closed when they finish, but it seems they can be closed without issuing the last update, so it looks like they aren't done when they are:

<img width="728" alt="Screen Shot 2021-07-10 at 10 34 09" src="https://user-images.githubusercontent.com/151929/125157297-76274480-e16a-11eb-8656-5853a10924e1.png">

**Comment by GF-Huang** [comment]
Why in my case always show the CPU count instead of `100`? 7.0.0a5

**Comment by minrk** [comment]
Probably because it's a DirectView, and the number is the number of *tasks* (messages) not items in the sequence.
