### ISSUE TITLE
Write a Python program to remove and print every third number from a list of numbers until the list becomes empty.

### ISSUE THREAD

**Issue by iamagreatman** [ipython/ipyparallel#527]
def remove_nums(int_list):
  #list starts with 0 index
  position = 3 - 1 
  idx = 0
  len_list = (len(int_list))
  while len_list>0:
    idx = (position+idx)%len_list -----------------# **_please explain..what is the use of % here and the whole in detail..please_**
    print(int_list.pop(idx))
    len_list -= 1  -------------------------------# **_please explain_**
nums = [10,20,30,40,50,60,70,80,90]
remove_nums(nums)

**Comment by minrk** [comment]
It looks like this issue was opened by mistake. That looks like a coding assignment, not a question for IPython Parallel. Feel free to open a new Issue if you have an issue using IPython Parallel.
