### ISSUE TITLE
'LoadBalancedView' object has no attribute 'push'

### ISSUE THREAD

**Issue by GF-Huang** [ipython/ipyparallel#537]

**Comment by minrk** [comment]
That's right. A load-balanced push wouldn't make a huge amount of sense, since you don't know where that data is going to go.

If you want to use pushed data with a load-balanced view, you can combine a direct view and load balanced view.

**Comment by GF-Huang** [comment]
> That's right. A load-balanced push wouldn't make a huge amount of sense, since you don't know where that data is going to go.
> 
> If you want to use pushed data with a load-balanced view, you can combine a direct view and load balanced view.

Could you show me the docs for differences of `DirectView` vs `LoadBalancedView` vs `BroadcastView`?

**Comment by minrk** [comment]
push/pull and scatter/gather are part of the DirectView docs [here](https://ipyparallel.readthedocs.io/en/latest/tutorial/direct.html#moving-python-objects-around). The [load-balanced docs](https://ipyparallel.readthedocs.io/en/latest/tutorial/task.html) only mention apply/map, and the [details docs](https://ipyparallel.readthedocs.io/en/latest/reference/details.html#data-movement) mention that data movement methods are unavailable on load-balanced views.

**Comment by GF-Huang** [comment]
The `load_balanced_view.map_async` seems not async, it block always. 7.0.0a5.

**Comment by minrk** [comment]
That doesn't appear to be true. With this test:

```python
import time
import ipyparallel as ipp

with ipp.Cluster(n=4) as rc:
    view = rc.load_balanced_view()
    tic = time.perf_counter()
    ar = view.map_async(time.sleep, [0.1] * 100)
    toc = time.perf_counter()
    print(f"Submitted {len(ar)} tasks in {toc-tic:.3f}s")
    ar.wait_interactive()
    print(f"Completed in {ar.wall_time:.1f}s")
```

you can see that tasks are submitted in ~200ms, while the actual work takes ~3s.
