### ISSUE TITLE
Example of how to use wait_interactive async result method()

### ISSUE THREAD

**Issue by washougal** [ipython/ipyparallel#54]
I created a question on stackoverflow: http://stackoverflow.com/questions/33061111/monitoring-status-of-ipyparallel-completion. Basically, looking through the async.py file I see that there is a wait_interactive method, but have not been able to figure out how to use it. I don't imagine I'm going to be the last to hope to get periodic updates during large jobs, so If I can get some clarification I'll submit a file that can be added to the examples folder to help others.

**Comment by minrk** [comment]
When you create an AsyncResult, e.g.

```python
ar = view.map_async(f, sequence)
```

You can call its `wait_interactive` method:

```python
ar.wait_interactive()
```

And it will show you how much progress it has made while it waits.
