### ISSUE TITLE
error using latest Ipyparallel version on Jupyter notebook

### ISSUE THREAD

**Issue by rishi1016** [ipython/ipyparallel#563]
Hi @minrk - I'm getting the following error when I try to use Ipyparallel v7.0.0b2 with Jupyter notebook and start an Ipython Cluster

<img width="1206" alt="Screen Shot 2021-08-30 at 5 11 09 PM" src="https://user-images.githubusercontent.com/36023059/131406222-b12a4364-9435-4cb2-8d6b-cc9e7f908b2e.png">

![Screen Shot 2021-08-30 at 5 08 09 PM](https://user-images.githubusercontent.com/36023059/131406242-671b6962-8494-41d1-bfce-d4cc5677f2ac.png)

this is working fine with the latest stable release - v6.3.0

I'd greatly appreciate your help fixing this, thanks,

**Comment by minrk** [comment]
Fixed by #564, thanks!
