### ISSUE TITLE
First argument 'f' of apply/apply_async/etc is too generic a name

### ISSUE THREAD

**Issue by alicedb2** [ipython/ipyparallel#573]
If it happen that the function passed to apply/apply_async/etc has a keyword argument `f` the command fails with

`apply_async() got multiple values for argument 'f'`

I know this can never be completely avoided but `f` is still too generic a name. Something longer/more explicit, if just `func`, could avoid this special case more often.

For now the only way to avoid this issue is to provide argument positionally to apply/etc all the way passed the submitted function's `f` keyword argument.

**Comment by minrk** [comment]
100%! We should change it to `__ipyparallel_f` or something similar.

**Comment by minrk** [comment]
I think it can also be worked around with `functools.partial`:

```python
view.apply(partial(my_func, f=whatever), other, args)
```
