### ISSUE TITLE
`ViewExecutor` context manager (`with` statement)

### ISSUE THREAD

**Issue by aplamada** [ipython/ipyparallel#612]
`ViewExecutor.shutdown()` is not waiting for the results.

Is this as expected?

**Comment by aplamada** [comment]
Awesome - I tested `ipyparallel==8.0.0b1` and it works as expected:
- `shutdown()` is doing the work,
- `ViewExecutor` scheduler is similar to the `LoadBalancedView` scheduler.

Many thanks, again!

**Comment by minrk** [comment]
Wonderful, thanks for testing!
