### ISSUE TITLE
Create default profile and the ipython folder if they don't exist

### ISSUE THREAD

**Issue by akhmerov** [ipython/ipyparallel#622]
`ipyparallel` will refuse to run if ipython profiles don't exist. This is different from ipython, which creates `.ipython` and the default profile on first run.

The additional impact of this problem is the behavior of the lab extension.

If `~/.ipython` is missing, opening the lab shows this ominous error message:

![image](https://user-images.githubusercontent.com/2069677/139311404-6f5c92ba-0732-4d23-980a-bcf2e51b6575.png)

In case this information is important, this is observed in ipyparallel `7.1.0` an jupyterlab `3.2.1`.

**Comment by Betristor** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/55777837/160062657-54cff775-4455-43b1-9b76-060ec0060ac2.png">

I got the same situation but in a jupyterlab within hub. No matter where I install the ipyparallel (in local environment or in global hub environment), this problem exists and keeps bothering me.

And the case is  just the same for dask-labextension, of which I assume the reason is the same.

**Comment by minrk** [comment]
@Betristor can you share the logs from the server? They should containe the relevant error.

**Comment by Betristor** [comment]
Sorry I'm late for reply. But where could I access the specific log of ipyparallel? I know how to investigate into logs for each user in jupyterhub. But it only shows that the ipyparallel is not successfully loaded.
![image](https://user-images.githubusercontent.com/55777837/160867945-fa92e299-30d4-4b83-b39c-9178f4bcb537.png)

**Comment by Betristor** [comment]
I'm sorry to say that, but today when I opened the jupyterlab again, the ipyparallel just works fine like nothing wrong happened before... I'm speechless, (╯°□°）╯︵ ┻━┻. But if you need the log, I could still offer it.

**Comment by minrk** [comment]
It's frustrating when things don't break when you need them to! Glad it's working for now, though.

If you can capture the logs if/when you see the error again, that will be a big help in tracking down what's wrong.

A 404 on the extension URL probably means a failure to load or find the extension, and likely a config issue - you can try `jupyter server extension list` and check the logs when the single-user server for if it says it is starting "Jupyter Notebook" or "Jupyter Server" (these are different implementations of the server, and have slightly different extension mechanisms).
