### ISSUE TITLE
No settings available for ipyparallel in JupyterLab

### ISSUE THREAD

**Issue by dmcooke** [ipython/ipyparallel#626]
1) There is no section for ipyparallel in the Advanced Settings Editor in JupyterLab
2) The 'Auto-start IPython Parallel' option in the Settings menu doesn't keep its value
3) I get the following errors output by `jupyter lab`
````
[W 2021-11-06 00:52:13.457 ServerApp] 404 GET /lab/api/settings/ipyparallel-labextension:plugin?1636185133251 (127.0.0.1): Schema not found: /home/dave/Software/jupyterlab/jupyter-venv/share/jupyter/lab/schemas/ipyparallel-labextension/plugin.json
[W 2021-11-06 00:52:13.457 LabApp] Schema not found: /home/dave/Software/jupyterlab/jupyter-venv/share/jupyter/lab/schemas/ipyparallel-labextension/plugin.json
[W 2021-11-06 00:52:13.458 LabApp] 404 GET /lab/api/settings/ipyparallel-labextension:plugin?1636185133251 (127.0.0.1) 4.03ms referer=http://localhost:8888/lab
````
I'm fairly sure that the `jupyter/schemaDir` key in `package.json` should have the value `"lab/schema"`, and not `"schema"`
(it should be a path relative to the `package.json` file in the source tree). Otherwise the schema file describing ipyparallel's config settings isn't installed.

With that change, installing from source leads to a `<prefix>/share/jupyter/labextensions/ipyparallel-labextension/schemas/ipyparallel-labextension/plugin.json`
file being installed. and the settings showing up as they should.

**Comment by minrk** [comment]
I think you're right, but also it looks like the schema is leftover from adapting dask-labextension. While the option is defined, it doesn't do anything. I think I may just remove it, though it could be implemented in the future. I think it may make more sense in dask than IPP, though, since dask has all kinds of monitoring tools hooked up to the 'active' cluster, which IPP does not.

**Comment by minrk** [comment]
A question, before I put too much time into it: did you run into this because you saw a setting and it didn't work, or because you actually wanted to enable the auto-start feature?

**Comment by dmcooke** [comment]
I saw error messages in my JupyterLab log, and that annoyed me ) So, yeah, I don't actually need the feature.

**Comment by minrk** [comment]
OK, I'll just remove it for now, then. Planning to release 8.0 tomorrow.
