### ISSUE TITLE
Not able to install IPython Clusters tab in Jupyter Notebook

### ISSUE THREAD

**Issue by cardosan** [ipython/ipyparallel#64]
I Followed the [readme](https://github.com/ipython/ipyparallel#install) but  the Clusters tab it is not showing up and when I launch the notebook I get:

`[W 16:30:03.356 NotebookApp] Collisions detected in jupyter_notebook_config.py and jupyter_notebook_config.json config files. jupyter_notebook_config.json has higher priority: {
      "NotebookApp": {
        "server_extensions": "<traitlets.config.loader.LazyConfigValue object at 0x7f3dab33beb8> ignored, using ['nbextensions']"
      }`

I am on linux mint 17.2 python 3 conda and already installed nbextension, any idea?

**Comment by cel4** [comment]
Instead of editing `jupyter_notebook_config.py`, edit `jupyter_notebook_config.json` and look for:

```
  "NotebookApp": {
    "server_extensions": [
      <some lines>
    ]
```

change this to:

```
  "NotebookApp": {
    "server_extensions": [
      <some lines>,
      "ipyparallel.nbextension"
    ]
```

**Comment by cardosan** [comment]
solved, thanks!

**Comment by thoth291** [comment]
It's not really working for me though.
My conda root environment is installed by admin and there is no way for me to update that .json file.
All what I can play with is my .py file. So is there any way to change the path/order to look for .json or something which might be helpful in my case?

**Comment by minrk** [comment]
@thoth291 you can still use the Python config:

```python
c.NotebookApp.server_extensions.append("ipyparallel.nbextension")
```

Or you can install/enable the extension for just you:

```
jupyter nbextension install --py ipyparallel --user
jupyter nbextension enable --py ipyparallel --user
jupyter serverextension enable --py ipyparallel --user
```

**Comment by thoth291** [comment]
Thanks.
I actually have found out that I can create my own .json file in my jupyter profile directory.
As an alternative I also asked admin to enable all sort of extensions in the root .json so that other users will not be affected.

**Comment by etlolap** [comment]
Where can I find jupyter_notebook_config.json? I can only find jupyter_notebook_config.py under home/.jupyter/.

**Comment by minrk** [comment]
Anywhere there is a `config.py`, a `config.json` can be placed next to it. However, if you are editing by hand, I recommend using the `.py` config files over the `.json` ones, as they are much easier to read/write/edit. The two are equivalent, but one is meant to be written by machines, the other by humans.
