### ISSUE TITLE
'CannedArray' object has no attribute 'pickled'

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipyparallel#65]
Have seen this once in code that normally doesn't produce this. Using Jupyter/iPython cluster. Related question ( http://stackoverflow.com/q/27596463 ). Related issue opened ( https://github.com/uqfoundation/dill/issues/134 ).

**Comment by minrk** [comment]
@jakirkham Python, package versions?

**Comment by jakirkham** [comment]
Sorry this is so gross.

    anaconda-client 1.1.0
    bokeh 0.10.0
    boost 1.57.0
    bottleneck 1.0.0
    cairo 1.12.18
    certifi 2015.9.6.2
    clyent 0.4.0
    conda 3.18.3
    conda-build 1.18.1
    conda-env 2.4.4
    decorator 4.0.4
    dill 0.2.4
    drmaa 0.7.6
    fftw 3.3.4
    fireworks 1.1.6
    flask 0.10.1
    flask-paginate 0.3.2
    fontconfig 2.11.1
    freetype 2.5.5
    funcsigs 0.4
    futures 3.0.3
    h5py 2.5.0
    hdf5 1.8.15.1
    icu 54.1
    ipykernel 4.1.1
    ipyparallel 4.0.2
    ipython 4.0.0
    ipython-notebook 4.0.4
    ipython_genutils 0.1.0
    ipywidgets 4.1.0
    itsdangerous 0.24
    jinja2 2.8
    jpeg 8d
    jsonschema 2.4.0
    jupyter_client 4.1.1
    jupyter_core 4.0.6
    libgcc 4.8.5
    libpng 1.6.17
    libsodium 1.0.3
    libtiff 4.0.2
    libxml2 2.9.2
    markupsafe 0.23
    matplotlib 1.4.3
    mistune 0.7.1
    mock 1.3.0
    mongodb 2.4.6
    monty 0.6.5
    nanshe 0.1.0a29
    nbconvert 4.0.0
    nbformat 4.0.1
    networkx 1.10
    nose 1.3.7
    notebook 4.0.6
    numpy 1.9.3

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time! I'm going to close this as super old and nondeterministic, but feel free to open again (especially with a repro example) if you are still seeing this.
