### ISSUE TITLE
install from git fails with FIPS-compliant nodejs

### ISSUE THREAD

**Issue by kloczek** [ipython/ipyparallel#653]
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w`
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

In this case sbove procedure fails on first step
```console
+ /usr/bin/python3 -sBm build -w
* Creating venv isolated environment...
* Installing packages in isolated environment... (jupyterlab>=3.0.0,==3.*, packaging, setuptools>=40.8.0, wheel)
* Getting dependencies for wheel...
running egg_info
creating ipyparallel.egg-info
writing manifest file 'ipyparallel.egg-info/SOURCES.txt'
no previously-included directories found matching 'lab/lib'
warning: no directories found matching 'ipyparallel/labextension'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '.git' found anywhere in distribution
warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
writing manifest file 'ipyparallel.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running pre_dist
yarn not found, ignoring yarn.lock file
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @lumino/coreutils@1.8.0" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.0.0" has unmet peer dependency "typanion@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.17", while you're on "1.21.1".
Done in 6.96s.
yarn run v1.21.1
$ jlpm run build:lib && jlpm run build:labextension
$ tsc
$ jupyter labextension build .
Building extension in .

Compilation starting…

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:70:8)
    at NormalModule._initBuildHash (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/node_modules/webpack/lib/NormalModule.js:880:17)
    at handleParseResult (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/node_modules/webpack/lib/NormalModule.js:946:10)
    at /home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/node_modules/webpack/lib/NormalModule.js:1040:4
    at processResult (/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/node_modules/webpack/lib/NormalModule.js:755:11)
    at /home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/node_modules/webpack/lib/NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
An error occurred.
subprocess.CalledProcessError: Command '['node', '/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/node_modules/@jupyterlab/builder/lib/build-labextension.js', '--core-path', '/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/jupyterlab/staging', '/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0']' returned non-zero exit status 1.
See the log file for details:  /tmp/jupyterlab-debug-o3qqk3av.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 261, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/build_meta.py", line 230, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/build_meta.py", line 158, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 173, in <module>
    setuptools.setup(**setup_args)
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/setupbase.py", line 131, in run
    self.run_command(pre_build.__name__)
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/tmp/build-env-lghtzk_q/lib64/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/setupbase.py", line 112, in run
    func()
  File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/setupbase.py", line 214, in builder
    run(npm_cmd + ['run', build_cmd], cwd=node_package)
  File "/home/tkloczko/rpmbuild/BUILD/ipyparallel-8.1.0/setupbase.py", line 275, in run
    return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-lghtzk_q/bin/jlpm', 'run', 'build:prod']' returned non-zero exit status 1.

ERROR Backend subproccess exited when trying to invoke build_wheel
```

**Comment by minrk** [comment]
This looks like a problem with the nodejs install. Can you share info about the node version, etc. in the build environment?

**Comment by kloczek** [comment]
Build env is mostly mine but actually nodejs still is from Fedora rawhide.
I'm using nodejs 16.13.1.

**Comment by minrk** [comment]
Seems to be a [nodejs issue](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported). I'm not sure if there's a fix required in our config or the nodejs install, invocation, or what.

**Comment by kloczek** [comment]
Still the same effect :/
Do you have maybe some recipe about how to avoid this kind of situations and/or are able to build now  `ipyparallel` somehow?

**Comment by minrk** [comment]
I don't know anything about that error, and don't _think_ it has anything to do with this package, but searching [suggests](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported):

    export NODE_OPTIONS=--openssl-legacy-provider

I don't know what that means or its implications, or what might be the reason your nodejs doesn't work. Do you have any `$OPENSSL*` environment variables?

**Comment by minrk** [comment]
I don't know enough about nodejs or fedora to know what's wrong, but after playing around a little, it seems like the nodejs 16 in rawhide doesn't really work yet ([npm isn't packaged yet](https://fedoraproject.org/wiki/Node.js/npm_update_status), but it should be a dependency of nodejs?).

If you can, maybe try running with nodejs:14?

**Comment by minrk** [comment]
@blink1073 have you seen anything like this invoking yarn during packaging?

**Comment by kloczek** [comment]
FYI: I;m usimg nodejs 16.14.1.

**Comment by blink1073** [comment]
Hahaha this is one of the things that led to my burnout on JupyterLab: https://github.com/jupyterlab/jupyterlab/issues/11248

**Comment by kloczek** [comment]
S what ios trhe solution for pep517 based buils in such cases? 🤔

**Comment by minrk** [comment]
@kloczek do you require regenerating javascript? Because you don't need to, they are part of the source distributions. Nodejs is not a build dependency unless you have a policy requirement to rebuild the js artifacts.

Here's a dockerfile that builds from a release without node:

```dockerfile
FROM python:3.9
RUN pip install build
ARG V=8.2.1
RUN curl -L -O https://pypi.io/packages/source/i/ipyparallel/ipyparallel-${V}.tar.gz
RUN tar -xzf ipyparallel-${V}.tar.gz
RUN cd ipyparallel-${V} \
 && python -m build --wheel . \
 && pip install ./dist/*.whl
```

**Comment by minrk** [comment]
@kloczek can you also try with the patch in #690 ? It may fix it, if I've read the above issues correctly. Thanks for the info @blink1073!

**Comment by kloczek** [comment]
> @kloczek do you require regenerating javascript? Because you don't need to, they are part of the source distributions. Nodejs is not a build dependency unless you have a policy requirement to rebuild the js artifacts.
> 
> Here's a dockerfile that builds from a release without node:
> 
> ```dockerfile
> FROM python:3.9
> RUN pip install build
> ARG V=8.2.1
> RUN curl -L -O https://pypi.io/packages/source/i/ipyparallel/ipyparallel-${V}.tar.gz
> RUN tar -xzf ipyparallel-${V}.tar.gz
> RUN cd ipyparallel-${V} \
>  && python -m build --wheel . \
>  && pip install ./dist/*.whl
> ```

As source input I'm using autogenerated by gihub tar ball from git tag and that prcess calls nodejs .. and what nodejs does fails.
Seccond thing is that in your procedure you are using `build` module without `--no-isolation` which meand that all necessary build dependencies are downooaded as .whl archives and locally installed resources are installed in venv.
I want to have build prcess 100% relaying ONLY on locally installed resources. That means that sooner or later I want to have build process which will be using all necessary nodejs packages intead downloaing them from public network.
That build process needs to be working witout acces to public network.

What I've copied here is from my devel system which have access to public networ.
If nodejs fails it means that sometbing is not defined or wrongly defined in locked versions of nodejs components.

**Comment by kloczek** [comment]
It is yet another reason why I preffer using VCS tar balls.
Realy quite big number of sdist tar balls is distriubuted without test suite or documentation which are only available in VCS.
As I'm trying to use execution of the test suite during build process those sdist tar balls are useless.
```console
[tkloczko@devel-g2v SPECS]$ grep %pytest python* | wc -l
750
```
Generally speaking there are only some rare cases when on using VCS tar balls there are some issues during build process.

**Comment by minrk** [comment]
> Generally speaking there are only some rare cases when on using VCS tar balls there are some issues during build process.

True. The reverse is also true :) it's just as rare for a published release to not work. We only have this issue because of the choice to do a development install instead of a standard install, which doesn't require nodejs at all.

**Comment by kloczek** [comment]
> he reverse is also true :)

Accoording to my observations ~5% of all checked by me sdist tar bals have some build issues.
It is way more often than on using VCS tar balls because modules developers are using VCS trees to generate pypi .whl archives.
