### ISSUE TITLE
%%px  --group-outputs=engine not grouping output by engine

### ISSUE THREAD

**Issue by chwrtlprmft** [ipython/ipyparallel#656]
It seems that the `--group-outputs=engine` option to the `%%px` magic does not actually group the output per engine ([also posted on stackoverflow](https://stackoverflow.com/posts/70531905/edit)).

```python
import ipyparallel as ipp
```

```python
rc = ipp.Client()
```

```python
%%px --targets 0
offset=0
```

```python
%%px --targets 1
offset=1
```

```python
%%px --targets 2
offset=2
```

```python
%%px --targets 3
offset=3
```

```python
%%px --group-outputs=engine
print(offset)
```

    [stdout:0] 0

    [stdout:1] 1

    [stdout:3] 3

    [stdout:2] 2

**Comment by minrk** [comment]
What would you expect the output to look like in this case?

The groupby only has an effect when there are _multiple_ kinds of outputs for each engine, e.g. stdout, stderr, rich display. If there's only stdout, group-outputs should have no effect.

**Comment by chwrtlprmft** [comment]
Well, i expected that all output (stdout and plots) would be grouped per engine, which I understood to mean it would be given in sequence for each engine with ascending engine number, i.e.:

```
[stdout:0] 0

[stdout:1] 1

[stdout:2] 2

[stdout:3] 3
```

Cell [17] in [this](https://ipyparallel.readthedocs.io/en/8.1.0/examples/Parallel%20Magics.html?highlight=group-outputs#Using-Parallel-Magics) page of the documentation looks like this is the case for stdout but not for output.

In my actual application, I want to do a calculation and a plot on each engine in parallel and then get the plots displayed in ascending engine order.

**Comment by chwrtlprmft** [comment]
Ok, I realized the purpose of that flag now and that i actually am after a functionality that would hypothetically better be named as `--sort-outputs=engine`.

Is there maybe a workaround to achieve sorting the outputs from a parallel cell by the target numbers of the engines? Right now I have to generate the plots sequentially after computing the underlying data in parallel, which is in pricipal fine, but the plot generation is kinda slow too, unfortunately.

**Comment by minrk** [comment]
I'll look into why it's not in order - that's a reasonable expectation and should be the default behavior. I don't think it needs a flag, that's just what it should do!

**Comment by minrk** [comment]
Sorry, spoke too soon - `%%px` displays outputs _as they arrive_ by default, so whoever finishes first will display first. If you add `--no-stream`, it will wait until results are finished before displaying them, and then they will be displayed in order:

```
%%px --no-stream --group-outputs=engine
```

**Comment by chwrtlprmft** [comment]
Ah, ok - that is exactly what i was looking for. Thank you :) .
