### ISSUE TITLE
ipyparallel does not seem to establish an MPI connection between hosts

### ISSUE THREAD

**Issue by airchaoz** [ipython/ipyparallel#676]
![image](https://user-images.githubusercontent.com/32660335/159836263-18a9002f-3506-4772-9da5-346bbc06c009.png)
This example is taken from the documentation, but the results obtained are not consistent with the documentation.

**Comment by minrk** [comment]
Can you tell me some more information about your OS, how mpi and mpi4py are installed?

**Comment by airchaoz** [comment]
![image](https://user-images.githubusercontent.com/32660335/159910684-5767a50a-98c2-4a91-8f5f-c0134348d3bd.png)
My other computer is also using this configuration, but does not have the above problem

**Comment by minrk** [comment]
Can you share the output of `print(rc.cluster.engine_set.get_output())`? That will show the output of the mpiexec process.

Also `rc.cluster.engine_set.process.cmdline()` will show the command it launched.

**Comment by airchaoz** [comment]
I'm very sorry, but I can't reproduce this problem anymore. ipyparallel works fine now

Before that, I ran this command: `pip install ipykernel`, but I'm not sure if that's what did it.
Anyway, thank you very much for your help!

**Comment by minrk** [comment]
glad it's working!
