### ISSUE TITLE
Use a flit-based backend?

### ISSUE THREAD

**Issue by blink1073** [ipython/ipyparallel#704]
I'd like to contribute a flit-based backend, which I think would greatly simplify things.

Instead of a 1000 line `setupbase.py` we could use an in-tree backend similar to what I tried in https://github.com/ipython/ipykernel/pull/927.

I had to abort that one because `ipykernel` ships with multiple top level entities, but `ipyparallel` does not.

**Comment by minrk** [comment]
I'd love that!
