### ISSUE TITLE
bug: flit_core >= 3.4.0 required

### ISSUE THREAD

**Issue by jhgoebbert** [ipython/ipyparallel#710]
`ipyparallel` needs the requirement `flit_core>=3.4.0` as minimum.
`build_editable` is used in [buildapi.py#L10](https://github.com/ipython/ipyparallel/blob/main/buildapi.py#L10) which was introduced with `flit_core==3.4.0` in https://github.com/pypa/flit/commit/2a8785811f61f9959e91376fa6337e677c94ce0e

It `flit_core<3.4.0` is installed one gets the error:  
`ImportError: cannot import name 'build_editable' from 'flit_core.buildapi' (/lib/python3.9/site-packages/flit_core/buildapi.py)`

You might want to fix this in [pyproject.toml#L4](https://github.com/ipython/ipyparallel/blob/main/pyproject.toml#L4)

**Comment by minrk** [comment]
Thanks, fixed by #714
