### ISSUE TITLE
imap - only a single engine is still used after a few iterations

### ISSUE THREAD

**Issue by tommedema** [ipython/ipyparallel#743]
I've setup an ipyparalle cluster which resulted in a decent speed up from 15 it/s to about 80-120 it/s:
<img width="245" alt="Screen Shot 2022-08-30 at 6 21 18 PM" src="https://user-images.githubusercontent.com/331833/187587761-7a366f59-3600-4aac-9062-12cd579e2413.png">

Sample code:

```
import ipyparallel as ipp
import os
    
clusterProcessesCount = os.cpu_count() # == 16

cluster = ipp.Cluster(n = clusterProcessesCount)
cluster.start_cluster_sync()
rc = cluster.connect_client_sync()
rc.wait_for_engines(clusterProcessesCount)
lview = rc.load_balanced_view()
dview = rc[:]

# ...

# push settings to child processes
dview.push(dict(
    cvTrainingFoldMinMatchCount = cvTrainingFoldMinMatchCount,
    cvTrainingFoldMaxMatchCount = cvTrainingFoldMaxMatchCount,
    cvEarlyAbandonMinPromisingSuccessRate = cvEarlyAbandonMinPromisingSuccessRate
))

# ....

for result in lview.imap(parallelTrainTestQuery, cvIndicesAndQueries, ordered = False, max_outstanding = 'auto'):            
            print(result)
```

Note that since I am using this for cross validation, I am referring to the the number of folds that were processed until the engines stop being used. After 2 folds (iterations of iterations) it is only using 1 engine out of 16:
<img width="1216" alt="Screen Shot 2022-08-31 at 5 35 48 AM" src="https://user-images.githubusercontent.com/331833/187588719-bf004d78-176a-42c9-bab3-d01dc26bc441.png">

There are no error messages that I can see. At the first fold all 16 engines are fully used at 100% CPU. I did notice that when I first boot the cluster there are various [warning messages](https://github.com/ipython/ipyparallel/issues/741), but none seem to stop the cluster from working.

Is there anything I can do to help resolve this?

**Comment by minrk** [comment]
Is there a chance the 100% cpu process is not an engine at all, but rather the notebook kernel or perhaps a scheduler? Can you tell which process that is (you can check the command-line of hte process with e.g. `psutil.Process(pid).cmdline()` or `ps ax`?

**Comment by tommedema** [comment]
@minrk thanks for the response!

ps ax gave me:

`1264   ??  Rs   1130:11.85 /Users/tommedema/opt/anaconda3/bin/python -m ipykern` 

also here are some screenshots from activity monitor:

<img width="545" alt="Screen Shot 2022-08-31 at 5 59 13 PM" src="https://user-images.githubusercontent.com/331833/187724906-77921803-9c8c-4772-bc33-03684fd6d1d2.png">
<img width="555" alt="Screen Shot 2022-08-31 at 5 59 08 PM" src="https://user-images.githubusercontent.com/331833/187724926-231028ee-1037-4d9d-947e-602c4f4a38bb.png">
<img width="562" alt="Screen Shot 2022-08-31 at 5 59 03 PM" src="https://user-images.githubusercontent.com/331833/187724934-3995ad1a-0db0-4edd-8171-efd4138e800c.png">

**Comment by minrk** [comment]
That means it's your kernel (the client) not any engines stuck doing work, perhaps processing incoming results. If you interrupt your notebook when this happens, do you get a traceback? How big are the `result` objects of your individual tasks? 300k is quite a few tasks. Depending on how many you have, you might want to add e.g. `chunksize=10` to bundle 10 function calls per IPython Parallel message.

**Comment by minrk** [comment]
Sorry, you're right - imap doesn't support chunksize yet.

That traceback shows it was waiting in your pandas append, not an IPP call. This could be a coincidence, but I suspect it's because appending a row to a pandas DataFrame makes a copy of the whole DataFrame. This gets expensive when you have 300k rows and are making a whole new 250k row data frame as each new row comes in.

Pre-allocating the whole DataFrame should be loads faster and less memory intensive:

```python
N = len(cvIndicesAndQueries)

cvResults = pd.DataFrame(
    columns=["query_index", "success_rate", "match_count", "max_distance"],
    # defining the index ensures all the rows are defined
    index=np.arange(0, N),
)
...
for i, result in enumerate(lview.imap(...)):
    ...
    # addressing an _existing_ row doesn't create a new DataFrame
    # or maybe the index should be query_index?
    cvResults.iloc[i] = {...}
...
```

**Comment by tommedema** [comment]
@minrk wow, very sharp! This helped tremendously. Thank you so much.
