### ISSUE TITLE
Unhelpful error if engines start before controller

### ISSUE THREAD

**Issue by slishak** [ipython/ipyparallel#75]
I'm starting an IPython cluster on an HPC cluster. My script to start the cluster first sends a job that starts ipcontroller, waits for 10 seconds, and then starts each engine 0.5 seconds apart. Occasionally, the ipcontroller job will take longer than 10 seconds to start (delay unrelated to ipyparallel, it's due to our HPC cluster), meaning the engines try to connect before the controller has started. I'm passing the engines the path to where the connection file should eventually exist, but seeing as the file does not exist yet the engines fail with the following message:

```
2015-11-23 08:16:50.073 [IPEngineApp] ERROR | Couldn't start the Engine
Traceback (most recent call last):
  File "\\hpc\python\lib\site-packages\ipyparallel\apps\ipengineapp.py", line 347, in init_engine
    connection_info=self.connection_info,
AttributeError: 'IPEngineApp' object has no attribute 'connection_info'
```

This seems to be because `IPEngineApp.load_connector_file` never gets called in `IPEngineApp.init_engine` because it doesn't wait for the url file. I guess I'm not supposed to be doing this (instead I should be telling it the IPython directory and the profile name, that way it should wait for the url file to arrive), but it would be nice if it would either fail more gracefully or just wait for the url file for the time specified by `IPEngineApp.wait_for_url_file` in this case.

**Comment by minrk** [comment]
You are right, it should wait for the connection file just the same, no matter how you specify its location.

**Comment by minrk** [comment]
Can you show your config files? I don't think it's the path specification that's preempting the wait, but something else that makes it think you have specified connection info without the connection file.

I'm currently inclined to remove that option, since I've never heard of anyone using it, and it's confusing, at best.

**Comment by slishak** [comment]
```
# Configuration file for ipengine.
c.BaseIPythonApplication.verbose_crash = True
c.BaseParallelApplication.log_to_file = True
c.BaseParallelApplication.work_dir = u'\\\\hpc\\tmp\\code'
c.EngineFactory.timeout = 10.0
```

```
# Configuration file for ipcontroller.
c.BaseIPythonApplication.verbose_crash = True
c.BaseParallelApplication.log_to_file = True
c.BaseParallelApplication.work_dir = u'\\\\hpc\\tmp\\code'
c.IPControllerApp.use_threads = True
c.RegistrationFactory.ip = u'*'
```

**Comment by slishak** [comment]
(I'm using the default value for `c.IPEngineApp.wait_for_url_file = 5`)
