### ISSUE TITLE
Print in multiprocessing.Process crashing the engine

### ISSUE THREAD

**Issue by Nimrod0901** [ipython/ipyparallel#836]
Hi, I'm running on a Python3.8 environment with ipyparallel 8.6.1.
```Python
import ipyparallel as ipp
rc = ipp.Cluster(n=1).start_and_connect_sync()
rc.active()
```
```Python
%%px -b
from multiprocessing import Process
def foo():
    print(42)

p = Process(target=foo)
p.start()
p.join()
```
Got the error,
```
engine set stopped xxxx, {'engines': {'0': {'exit_code'; <Negsignal.SIGABRT: -6>, 'pid': xxxx, 'identifier': '0'}}, {'exit_code'; <Negsignal.SIGABRT: -6>}
```
Let me know if you need more info or help.

**Comment by minrk** [comment]
More info would help, because the given example doesn't work for other reasons for me:


```
AttributeError: Can't get attribute 'foo' on <module '__main__' (built-in)>
```

but if I change it to `p = Process(target=print, args=(42,))` to avoid looking up `foo` in nonexistent `__main__`, then I see:

```
[stdout:0] 42
```

and no errors.

Can you share the output of `pip freeze` and Python version, OS?

**Comment by Nimrod0901** [comment]
Thanks for reply!

`Process(target=print, args=(42, ))` also gives me the same error msg.
Also, I tested it in non-interactive environment, the problem still occured.

Python version: 3.8.10 (GCC 9.4.0)
OS: Ubuntu 20.04.4 LTS
Due to the network limitation, I can't show you the full output of `pip freeze` but some maybe revelant.
```
ipyparallel==8.6.1
jupyter==1.0.0
jupyter-client==7.3.5
jupyter-core==4.11.1
```

**Comment by minrk** [comment]
When I run this in an empty ubuntu 20:04 container, I don't get the captured output, but I also don't get any errors:

```
# pip freeze
asttokens==2.4.0
backcall==0.2.0
comm==0.1.4
debugpy==1.7.0
decorator==5.1.1
entrypoints==0.4
executing==1.2.0
importlib-metadata==6.8.0
ipykernel==6.25.2
ipyparallel==8.6.1
ipython==8.12.2
jedi==0.19.0
jupyter_client==8.3.1
jupyter_core==5.3.1
matplotlib-inline==0.1.6
nest-asyncio==1.5.7
packaging==23.1
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==3.10.0
prompt-toolkit==3.0.39
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.16.1
python-dateutil==2.8.2
pyzmq==25.1.1
six==1.16.0
stack-data==0.6.2
tornado==6.3.3
tqdm==4.66.1
traitlets==5.9.0
typing_extensions==4.7.1
wcwidth==0.2.6
zipp==3.16.2
```

**Comment by Nimrod0901** [comment]
```Bash
ipykernel==6.16.0
ipyparallel==8.6.1
ipython==8.5.0
ipython-genutils==0.2.0
ipywidgets==8.0.2
```
Hope this help

**Comment by minrk** [comment]
Try upgrading ipykernel and ipython. ipykernel is the package most likely to be relevant.

**Comment by Nimrod0901** [comment]
Upgrading ipykernel and ipython doesn't work, but upgrading pyzmq does fix this problem. 24.0.1 -> 25.1.1

Since it's not a issue of ipyparallel, I'll close it. Thanks for your patience.
