### ISSUE TITLE
Tasks DB not cleaned up after `ipcluster stop`

### ISSUE THREAD

**Issue by jakirkham** [ipython/ipyparallel#84]
Discovered after the database swelled up to 2/3 of TB after many runs. It would be nice if this was cleaned up on cluster shutdown. If that is intended behavior, then it appears not to be working.

**Comment by minrk** [comment]
It is in fact the intended behavior for the task database to persist because it allows result retrieval even after the Hub has died.

**Comment by minrk** [comment]
You can clear the task database with a Client when you are done, if that's what you want:

    client.purge_hub_results('all')

**Comment by jakirkham** [comment]
So, I tried starting up the cluster and running `client.purge_hub_results('all')` and also tried running `client.purge_everything()` to no avail. To be clear, this is in regard to data from a previous cluster session. Is there another way I should be doing this?

**Comment by minrk** [comment]
which db backend are you using?

**Comment by jakirkham** [comment]
SQLite

**Comment by minrk** [comment]
Thanks, I'll investigate why it's not doing the right thing. It may be something that I've forgotten about.

**Comment by minrk** [comment]
Can you share your `tasks.db` file, perhaps? I just tested this with master, and verified that running the Hub for a while, stopping it, starting a new one, and calling `Client.purge_everything()` *does* delete everything in the task database.

**Comment by jakirkham** [comment]
Hmm...sharing the database may be tricky. It often gets quite large during a run so I would have to think of the best way to share it. Also, there is the concern of non-published data being in the database. Let me think of what would be best to do this.

**Comment by minrk** [comment]
That's perfectly understandable. I'm just trying to think of the best way to see what's up, since it seems to be cleaning up over here.

You can perhaps try doing some basic SQLite browsing of the file, to see about tables/rows, etc. before/after purge.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Feel free to open a new Issue if you are still having this trouble.
