### ISSUE TITLE
Question: engines and databases

### ISSUE THREAD

**Issue by dineshbvadhia** [ipython/ipyparallel#855]
On a single n-core machine, each core is running an engine. Can each engine access their own (local) sqlite database residing on main storage ie. an n-core machine with n-engines and n-databases?

**Comment by minrk** [comment]
>  Can each engine access their own (local) sqlite database residing on main storage ie. an n-core machine with n-engines and n-databases?

Yes, you can run arbitrary code in each engine, so each engine can connect to its own sqlite database. You can use PIDs or engine IDs to differentiate them.
