### ISSUE TITLE
60s timeout on get_connection_info() is not configurable

### ISSUE THREAD

**Issue by rjplevin** [ipython/ipyparallel#867]
I'm having occasional timeouts in get_connection_info() but there's no configuration variable to change the 60 timeout. It's hardcoded in the argument default in the ControllerLauncher class in launcher.py and not modified in the calls to the method in cluster.py.

Is there any reason not to expose this timeout parameter in the config files?

**Comment by minrk** [comment]
> Is there any reason not to expose this timeout parameter in the config files?

There is not! #872
