### ISSUE TITLE
please release/tag/pypi the current version as it supports JupyterLab 4.x

### ISSUE THREAD

**Issue by jhgoebbert** [ipython/ipyparallel#868]
Hello everyone,

thank you for this great software package.

`ipyparallel` supports JupyterLab 4 since September last year [1].
But until now there has been no new official release/tag/pypi with this important update, yet.

Are there important reasons to wait for a new release of ipyparallel?
Can you tag the current version?

Best regards,
Jens Henrik

[1] https://github.com/ipython/ipyparallel/commit/bc8dac15795744eeb1f0e5c5470e7a5194f475cc

**Comment by minrk** [comment]
I'll do that today, thanks for the reminder

**Comment by jhgoebbert** [comment]
Great! Thank you!
