### ISSUE TITLE
command-line flag for --ip=*

### ISSUE THREAD

**Issue by dereneaton** [ipython/ipyparallel#89]
The simplest way I've found to connect to a multi-node HPC setup has been to use qsub to connect to multiple compute nodes, and then to use `ipcluster start` with --Engines=MPI to talk to all the nodes, like below: 

```
## from Login node connect interactively (or not) to 3 nodes with 8 cpus each
qsub -I -q {queue_name} -l nodes=3:ppn=8

## ... wait for connections to establish

## Now on the compute node run ipcluster with MPI setup
ipcluster start --n 24 --Engines=MPI --daemon

## run ipyparallel script which shows I'm connected to multiple hostnames
...
```

However, following the documentation I found I also had to create a new IPython profile and manually edit the ipcluster_config.py file setting `c.HubFactory.ip = '*'` to get the client to view all nodes.

Since that is the only variable that needs to be edited by hand in order to setup an MPI connection across multiple nodes on an HPC it seems it would really handy if it could just be set with a flag from ipcluster, like below:
```
ipcluster start --n 24 --Engines=MPI --ip=* --daemon
```

As a separate question: I also tried using the `PBS` setup through ipcluster, but I'm not sure I understand the intended workflow for that mode. It seems that once the templates are setup and submitted ipcluster will be connected to multiple nodes/engines, but the user will still be left hanging out on the Login node, which doesn't seem ideal. Should a user generally login to a compute node, and then submit ipcontroller to another compute node, and ipengines to multiple other nodes. That setup seems like it would always require more requests, and thus likely more wait times. Perhaps a more detailed example of the intended use of the PBS mode would make it more clear.  Thanks!

**Comment by minrk** [comment]
Since `--ip` is an arg to ipcontroller, neither `ipcluster_config` nor `ipcluster --ip=*` will work, since those configure only the wrapper. To use this, put the `HubFactory` line in your `ipcontroller_config.py`. I've added support for `ipcluster start --ip=` in #90
