### ISSUE TITLE
Logging messages from engines

### ISSUE THREAD

**Issue by mccarthyryanc** [ipython/ipyparallel#91]
I am looking for a good way to log messages from the running engines. I noticed [iopubwatcher.py](https://github.com/ipython/ipyparallel/blob/master/examples/iopubwatcher.py) and have used something similar, but I was looking for something more robust. Currently, I start the watcher and then launch my code in a separate process and it is starting to get a little messy.

**Comment by minrk** [comment]
I don't know what more robust means in this case. What exactly do you want it to do?

**Comment by mccarthyryanc** [comment]
I guess what I was looking for was something that extended the Logger class from the logging package so I could get logging messages from engines with something like:
```python
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger()

def func(logger):
    logger.debug("hostname: %s", socket.gethostname())
    logger.warning("hostname: %s", socket.gethostname())

c = Client()
dv = c[:]
dv.apply_async(func,range(10),{'logger':logger})
```
Right now I just capture stdout from the engines in a similar manner to what's done in iopubwatcher.py. Perhaps that isn't the best method for logging, though.

**Comment by RexFuzzle** [comment]
Did you manage to get something working with the logger class? 
Ran into a similar problem and it works in multiprocessing, but not ipyparallel.

**Comment by mccarthyryanc** [comment]
@RexFuzzle I didn't get a logger class working. What I am doing now is basically running main from [iopubwatcher.py](https://github.com/ipython/ipyparallel/blob/7202ad378d2ed3f3140899ddeef36c8bf47bcc48/examples/iopubwatcher.py) with multiprocessing.Process and writing output to a file instead of stdout.

**Comment by DrSAR** [comment]
I'm not going to pretend I understand what is going on here but in the [logging cookbook](git push --set-upstream origin logging.remastered
) there is mention of a ZeroMQ ‘publish’ socket in conjunction with a ZeroMQ ‘subscribe’ socket. Maybe that's the the way to pass your engine produced log chatter back to the hub?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. I’m especially closing old “how to” or debugging questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

The 'modern' Jupyter approach I'd use for logging special messages is to use displaypub with custom mimetypes, which you can then watch for like the iopub watcher:

```python
from IPython.display import publish_display_data
publish_display_data({"text/x-my-log": "log-message"})
```
